//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap kimidClearList {
            get {
                object obj = ResourceManager.GetObject("kimidClearList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidCopy {
            get {
                object obj = ResourceManager.GetObject("kimidCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidCut {
            get {
                object obj = ResourceManager.GetObject("kimidCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidDelete {
            get {
                object obj = ResourceManager.GetObject("kimidDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFilter {
            get {
                object obj = ResourceManager.GetObject("kimidFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNewPatternCategory {
            get {
                object obj = ResourceManager.GetObject("kimidNewPatternCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidPaLogo {
            get {
                object obj = ResourceManager.GetObject("kimidPaLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidPaste {
            get {
                object obj = ResourceManager.GetObject("kimidPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidRefresh {
            get {
                object obj = ResourceManager.GetObject("kimidRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Character.
        /// </summary>
        internal static string kstidAmbiguousBaseCharHdg {
            get {
                return ResourceManager.GetString("kstidAmbiguousBaseCharHdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a base character..
        /// </summary>
        internal static string kstidAmbiguousBaseCharMissingMsg {
            get {
                return ResourceManager.GetString("kstidAmbiguousBaseCharMissingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your base character must be contained\nwithin its associated ambiguous sequence..
        /// </summary>
        internal static string kstidAmbiguousBaseCharNotInTransMsg {
            get {
                return ResourceManager.GetString("kstidAmbiguousBaseCharNotInTransMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat as one unit?.
        /// </summary>
        internal static string kstidAmbiguousConvertHdg {
            get {
                return ResourceManager.GetString("kstidAmbiguousConvertHdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Pattern.
        /// </summary>
        internal static string kstidAmbiguousCVPatternHdg {
            get {
                return ResourceManager.GetString("kstidAmbiguousCVPatternHdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string kstidAmbiguousSeqHdg {
            get {
                return ResourceManager.GetString("kstidAmbiguousSeqHdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A base character may not be specified\nuntil you have specified an ambiguous sequence..
        /// </summary>
        internal static string kstidAmbiguousTransMissingMsg {
            get {
                return ResourceManager.GetString("kstidAmbiguousTransMissingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consonants.
        /// </summary>
        internal static string kstidConChartHTMLChartName {
            get {
                return ResourceManager.GetString("kstidConChartHTMLChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}ConsonantChart.html.
        /// </summary>
        internal static string kstidConChartHTMLFileName {
            get {
                return ResourceManager.GetString("kstidConChartHTMLFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the saved chart?.
        /// </summary>
        internal static string kstidConfirmSavedChartRemoval {
            get {
                return ResourceManager.GetString("kstidConfirmSavedChartRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consonant Chart.
        /// </summary>
        internal static string kstidConsonantChartViewText {
            get {
                return ResourceManager.GetString("kstidConsonantChartViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consonant Chart View (Ctrl+Alt+C).
        /// </summary>
        internal static string kstidConsonantChartViewToolTip {
            get {
                return ResourceManager.GetString("kstidConsonantChartViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Corpus.
        /// </summary>
        internal static string kstidDataCorpusHTMLChartName {
            get {
                return ResourceManager.GetString("kstidDataCorpusHTMLChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}DataCorpus.html.
        /// </summary>
        internal static string kstidDataCorpusHTMLFileName {
            get {
                return ResourceManager.GetString("kstidDataCorpusHTMLFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Corpus.
        /// </summary>
        internal static string kstidDataCorpusViewText {
            get {
                return ResourceManager.GetString("kstidDataCorpusViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Corpus View (Ctrl+Alt+D).
        /// </summary>
        internal static string kstidDataCorpusViewToolTip {
            get {
                return ResourceManager.GetString("kstidDataCorpusViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed in source as:.
        /// </summary>
        internal static string kstidExperimentalTransGridCol1 {
            get {
                return ResourceManager.GetString("kstidExperimentalTransGridCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to one of the following options:.
        /// </summary>
        internal static string kstidExperimentalTransGridCol2 {
            get {
                return ResourceManager.GetString("kstidExperimentalTransGridCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click, press enter on, or drag to a class\nto insert it into the current search pattern.
        /// </summary>
        internal static string kstidFFClassListToolTip {
            get {
                return ResourceManager.GetString("kstidFFClassListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patterns &amp; Pattern Building.
        /// </summary>
        internal static string kstidFFSliderPanelText {
            get {
                return ResourceManager.GetString("kstidFFSliderPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide record pane.
        /// </summary>
        internal static string kstidHideRecPaneToolTip {
            get {
                return ResourceManager.GetString("kstidHideRecPaneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load the &apos;{0}&apos; project?.
        /// </summary>
        internal static string kstidLoadNewProjectQuestion {
            get {
                return ResourceManager.GetString("kstidLoadNewProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string kstidMainWindowCaption {
            get {
                return ResourceManager.GetString("kstidMainWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The training file &apos;{0}&apos; is missing..
        /// </summary>
        internal static string kstidMissingTrainingFileMsg {
            get {
                return ResourceManager.GetString("kstidMissingTrainingFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0} Project File.
        /// </summary>
        internal static string kstidPAFilesCaptionOFD {
            get {
                return ResourceManager.GetString("kstidPAFilesCaptionOFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to {0} XML.
        /// </summary>
        internal static string kstidPAXMLExportCaptionSFD {
            get {
                return ResourceManager.GetString("kstidPAXMLExportCaptionSFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Values:\n{0}.
        /// </summary>
        internal static string kstidPhoneInventoryPhoneInfo {
            get {
                return ResourceManager.GetString("kstidPhoneInventoryPhoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Inventory.
        /// </summary>
        internal static string kstidPhoneInventoryViewText {
            get {
                return ResourceManager.GetString("kstidPhoneInventoryViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Inventory View (Ctrl+Alt+P).
        /// </summary>
        internal static string kstidPhoneInventoryViewToolTip {
            get {
                return ResourceManager.GetString("kstidPhoneInventoryViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a saved chart with the name &quot;{0}&quot;..
        /// </summary>
        internal static string kstidSavedChartNameAlreadyExistsMsg {
            get {
                return ResourceManager.GetString("kstidSavedChartNameAlreadyExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a saved chart with the name &quot;{0}&quot;.\nDo you want it overwritten?.
        /// </summary>
        internal static string kstidSavedChartNameAlreadyExistsOverwriteMsg {
            get {
                return ResourceManager.GetString("kstidSavedChartNameAlreadyExistsOverwriteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search pattern in the form:\n[Search Item]/[Environment Before]__[Environment After].
        /// </summary>
        internal static string kstidSearchPatternTooltip {
            get {
                return ResourceManager.GetString("kstidSearchPatternTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results ({0} Records).
        /// </summary>
        internal static string kstidSearchResultWordListWindowCaption {
            get {
                return ResourceManager.GetString("kstidSearchResultWordListWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string kstidSearchViewText {
            get {
                return ResourceManager.GetString("kstidSearchViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search View (Ctrl+Alt+S).
        /// </summary>
        internal static string kstidSearchViewToolTip {
            get {
                return ResourceManager.GetString("kstidSearchViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show record pane.
        /// </summary>
        internal static string kstidShowRecPaneToolTip {
            get {
                return ResourceManager.GetString("kstidShowRecPaneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unapplied changes in the phone inventory view. Would you like to save those changes?.
        /// </summary>
        internal static string kstidUnAppliedPhoneInventoryChangesMsg {
            get {
                return ResourceManager.GetString("kstidUnAppliedPhoneInventoryChangesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vowels.
        /// </summary>
        internal static string kstidVowChartHTMLChartName {
            get {
                return ResourceManager.GetString("kstidVowChartHTMLChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}VowelChart.html.
        /// </summary>
        internal static string kstidVowChartHTMLFileName {
            get {
                return ResourceManager.GetString("kstidVowChartHTMLFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vowel Chart.
        /// </summary>
        internal static string kstidVowelChartViewText {
            get {
                return ResourceManager.GetString("kstidVowelChartViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vowel Chart View (Ctrl+Alt+V).
        /// </summary>
        internal static string kstidVowelChartViewToolTip {
            get {
                return ResourceManager.GetString("kstidVowelChartViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} Records).
        /// </summary>
        internal static string kstidWordListWindowCaption {
            get {
                return ResourceManager.GetString("kstidWordListWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first choose &quot;Fill Chart&quot; before seeing search results..
        /// </summary>
        internal static string kstidXYChartFillChartMsg {
            get {
                return ResourceManager.GetString("kstidXYChartFillChartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts &amp; Chart Building.
        /// </summary>
        internal static string kstidXYChartsSliderPanelText {
            get {
                return ResourceManager.GetString("kstidXYChartsSliderPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Charts.
        /// </summary>
        internal static string kstidXYChartsViewText {
            get {
                return ResourceManager.GetString("kstidXYChartsViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Charts View (Ctrl+Alt+X).
        /// </summary>
        internal static string kstidXYChartsViewToolTip {
            get {
                return ResourceManager.GetString("kstidXYChartsViewToolTip", resourceCulture);
            }
        }
    }
}
