//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.FiltersAddOn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.FiltersAddOn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap kimidFilter {
            get {
                object obj = ResourceManager.GetObject("kimidFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFilterSmall {
            get {
                object obj = ResourceManager.GetObject("kimidFilterSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        internal static string kstidBeginsWith {
            get {
                return ResourceManager.GetString("kstidBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string kstidContains {
            get {
                return ResourceManager.GetString("kstidContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of {0}.
        /// </summary>
        internal static string kstidCopiedNamePrefix {
            get {
                return ResourceManager.GetString("kstidCopiedNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not begins with.
        /// </summary>
        internal static string kstidDoesNotBeginsWith {
            get {
                return ResourceManager.GetString("kstidDoesNotBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        internal static string kstidDoesNotContain {
            get {
                return ResourceManager.GetString("kstidDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not ends with.
        /// </summary>
        internal static string kstidDoesNotEndsWith {
            get {
                return ResourceManager.GetString("kstidDoesNotEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string kstidEndsWith {
            get {
                return ResourceManager.GetString("kstidEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string kstidEquals {
            get {
                return ResourceManager.GetString("kstidEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter &apos;{0}&apos; already exists..
        /// </summary>
        internal static string kstidFilterNameExistsMsg {
            get {
                return ResourceManager.GetString("kstidFilterNameExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        internal static string kstidGreaterThan {
            get {
                return ResourceManager.GetString("kstidGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal.
        /// </summary>
        internal static string kstidGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("kstidGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        internal static string kstidLessThan {
            get {
                return ResourceManager.GetString("kstidLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than or equal.
        /// </summary>
        internal static string kstidLessThanOrEqual {
            get {
                return ResourceManager.GetString("kstidLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        internal static string kstidMatches {
            get {
                return ResourceManager.GetString("kstidMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Filter {0}.
        /// </summary>
        internal static string kstidNewFilterName {
            get {
                return ResourceManager.GetString("kstidNewFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Filter).
        /// </summary>
        internal static string kstidNoFilterText {
            get {
                return ResourceManager.GetString("kstidNoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string kstidNormal {
            get {
                return ResourceManager.GetString("kstidNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equals.
        /// </summary>
        internal static string kstidNotEquals {
            get {
                return ResourceManager.GetString("kstidNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (OTHER FILTER).
        /// </summary>
        internal static string kstidOtherFilterFieldName {
            get {
                return ResourceManager.GetString("kstidOtherFilterFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist.
        /// </summary>
        internal static string kstidPathDoesNotExist {
            get {
                return ResourceManager.GetString("kstidPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path exists.
        /// </summary>
        internal static string kstidPathExists {
            get {
                return ResourceManager.GetString("kstidPathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Search Pattern.
        /// </summary>
        internal static string kstidPhoneticSrchPtrn {
            get {
                return ResourceManager.GetString("kstidPhoneticSrchPtrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string kstidRegExp {
            get {
                return ResourceManager.GetString("kstidRegExp", resourceCulture);
            }
        }
    }
}
