<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" indent="yes"/>
<!--
    <xsl:template match="@* | node()">
        <xsl:copy>
            <xsl:apply-templates select="@* | node()"/>
        </xsl:copy>
    </xsl:template>
-->
	<xsl:template match="ArrayOfAmbiguousSequence">
		<ambiguousSequences>
			<xsl:apply-templates/>
		</ambiguousSequences>
	</xsl:template>
	<xsl:template match="AmbiguousSequence">
		<sequence literal="{@Unit}" primaryBase="{@BaseChar}" unit="{@Convert}" generated="{@IsAutoGeneratedDefault}" />
	</xsl:template>
</xsl:stylesheet>
