//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.ResourceStuff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChartsTMStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChartsTMStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.ResourceStuff.ChartsTMStrings", typeof(ChartsTMStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Following Column.
        /// </summary>
        public static string kstidCharChartAddColAfterText {
            get {
                return ResourceManager.GetString("kstidCharChartAddColAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Preceding  Column.
        /// </summary>
        public static string kstidCharChartAddColBeforeText {
            get {
                return ResourceManager.GetString("kstidCharChartAddColBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;dd Following Heading.
        /// </summary>
        public static string kstidCharChartAddColHeadingAfterText {
            get {
                return ResourceManager.GetString("kstidCharChartAddColHeadingAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Preceding Heading.
        /// </summary>
        public static string kstidCharChartAddColHeadingBeforeText {
            get {
                return ResourceManager.GetString("kstidCharChartAddColHeadingBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;dd Following Row.
        /// </summary>
        public static string kstidCharChartAddRowAfterText {
            get {
                return ResourceManager.GetString("kstidCharChartAddRowAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Preceding Row.
        /// </summary>
        public static string kstidCharChartAddRowBeforeText {
            get {
                return ResourceManager.GetString("kstidCharChartAddRowBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;dd Following Heading.
        /// </summary>
        public static string kstidCharChartAddRowHeadingAfterText {
            get {
                return ResourceManager.GetString("kstidCharChartAddRowHeadingAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Preceding Heading.
        /// </summary>
        public static string kstidCharChartAddRowHeadingBeforeText {
            get {
                return ResourceManager.GetString("kstidCharChartAddRowHeadingBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Label.
        /// </summary>
        public static string kstidCharChartEditLabelText {
            get {
                return ResourceManager.GetString("kstidCharChartEditLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;Left.
        /// </summary>
        public static string kstidCharChartMoveColLeftText {
            get {
                return ResourceManager.GetString("kstidCharChartMoveColLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;Right.
        /// </summary>
        public static string kstidCharChartMoveColRightText {
            get {
                return ResourceManager.GetString("kstidCharChartMoveColRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Heading and its Empty Column(s).
        /// </summary>
        public static string kstidCharChartRemoveColHeadingText {
            get {
                return ResourceManager.GetString("kstidCharChartRemoveColHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Empty &amp;Column.
        /// </summary>
        public static string kstidCharChartRemoveColText {
            get {
                return ResourceManager.GetString("kstidCharChartRemoveColText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Heading and its Empty Row(s).
        /// </summary>
        public static string kstidCharChartRemoveRowHeadingText {
            get {
                return ResourceManager.GetString("kstidCharChartRemoveRowHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Empty &amp;Row.
        /// </summary>
        public static string kstidCharChartRemoveRowText {
            get {
                return ResourceManager.GetString("kstidCharChartRemoveRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string kstidCharChartSearchContextMenuText {
            get {
                return ResourceManager.GetString("kstidCharChartSearchContextMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show Subheadings.
        /// </summary>
        public static string kstidCharChartShowSubHeadingsText {
            get {
                return ResourceManager.GetString("kstidCharChartShowSubHeadingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al&amp;one.
        /// </summary>
        public static string kstidChartPhoneSearchAloneText {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchAloneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for phone alone.
        /// </summary>
        public static string kstidChartPhoneSearchAloneToolTip {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchAloneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Anywhere.
        /// </summary>
        public static string kstidChartPhoneSearchAnywhereText {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchAnywhereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for phone anywhere.
        /// </summary>
        public static string kstidChartPhoneSearchAnywhereToolTop {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchAnywhereToolTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word &amp;Finally.
        /// </summary>
        public static string kstidChartPhoneSearchFinalText {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchFinalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for phone word finally.
        /// </summary>
        public static string kstidChartPhoneSearchFinalToolTip {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchFinalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word &amp;Initially.
        /// </summary>
        public static string kstidChartPhoneSearchInitialText {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for phone word initially.
        /// </summary>
        public static string kstidChartPhoneSearchInitialToolTip {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchInitialToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word &amp;Medial.
        /// </summary>
        public static string kstidChartPhoneSearchMedialText {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchMedialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for phone word medial.
        /// </summary>
        public static string kstidChartPhoneSearchMedialToolTip {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchMedialToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string kstidChartPhoneSearchText {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Phone.
        /// </summary>
        public static string kstidChartPhoneSearchToolTip {
            get {
                return ResourceManager.GetString("kstidChartPhoneSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        public static string kstidChartTBAddText {
            get {
                return ResourceManager.GetString("kstidChartTBAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rows, Columns and Headings.
        /// </summary>
        public static string kstidChartTBAddToolTip {
            get {
                return ResourceManager.GetString("kstidChartTBAddToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;ollowing Column.
        /// </summary>
        public static string kstidChartTBMenuAddColAfterText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddColAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;receding Column.
        /// </summary>
        public static string kstidChartTBMenuAddColBeforeText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddColBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follo&amp;wing Column Heading.
        /// </summary>
        public static string kstidChartTBMenuAddColHeadingAfterText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddColHeadingAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre&amp;ceding Column Heading.
        /// </summary>
        public static string kstidChartTBMenuAddColHeadingBeforeText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddColHeadingBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Following Row.
        /// </summary>
        public static string kstidChartTBMenuAddRowAfterText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddRowAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Preceding Row.
        /// </summary>
        public static string kstidChartTBMenuAddRowBeforeText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddRowBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fo&amp;llowing Row Heading.
        /// </summary>
        public static string kstidChartTBMenuAddRowHeadingAfterText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddRowHeadingAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr&amp;eceding Row Heading.
        /// </summary>
        public static string kstidChartTBMenuAddRowHeadingBeforeText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuAddRowHeadingBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignored Suprasegmentals.
        /// </summary>
        public static string kstidChartTBMenuIgnoredCharsParentText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuIgnoredCharsParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Column H&amp;eading.
        /// </summary>
        public static string kstidChartTBMenuRemoveColHeadingText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuRemoveColHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active &amp;Column.
        /// </summary>
        public static string kstidChartTBMenuRemoveColText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuRemoveColText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;All Empty Rows &amp;&amp; Columns.
        /// </summary>
        public static string kstidChartTBMenuRemoveEmptyRowsAndColsText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuRemoveEmptyRowsAndColsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Row &amp;Heading.
        /// </summary>
        public static string kstidChartTBMenuRemoveRowHeadingText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuRemoveRowHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active &amp;Row.
        /// </summary>
        public static string kstidChartTBMenuRemoveRowText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuRemoveRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore &amp;Default Layout.
        /// </summary>
        public static string kstidChartTBMenuRestoreDefaultText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuRestoreDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Column Heading&apos;s Subheadings.
        /// </summary>
        public static string kstidChartTBMenuShowColSubHeadingsText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuShowColSubHeadingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Row Heading&apos;s Subheadings.
        /// </summary>
        public static string kstidChartTBMenuShowRowSubHeadingsText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuShowRowSubHeadingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Uncertain Phones.
        /// </summary>
        public static string kstidChartTBMenuShowUncertainPhonesText {
            get {
                return ResourceManager.GetString("kstidChartTBMenuShowUncertainPhonesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        public static string kstidChartTBRemoveText {
            get {
                return ResourceManager.GetString("kstidChartTBRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Rows, Columns and Headings.
        /// </summary>
        public static string kstidChartTBRemoveToolTip {
            get {
                return ResourceManager.GetString("kstidChartTBRemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vie&amp;w.
        /// </summary>
        public static string kstidChartTBViewText {
            get {
                return ResourceManager.GetString("kstidChartTBViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string kstidChartTBViewToolTip {
            get {
                return ResourceManager.GetString("kstidChartTBViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Histogram.
        /// </summary>
        public static string kstidShowHistogramText {
            get {
                return ResourceManager.GetString("kstidShowHistogramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string kstidShowHistogramToolTip {
            get {
                return ResourceManager.GetString("kstidShowHistogramToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HTML Chart.
        /// </summary>
        public static string kstidShowHtmlChartText {
            get {
                return ResourceManager.GetString("kstidShowHtmlChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HTML Chart.
        /// </summary>
        public static string kstidShowHtmlChartToolTip {
            get {
                return ResourceManager.GetString("kstidShowHtmlChartToolTip", resourceCulture);
            }
        }
    }
}
