//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.ResourceStuff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpTopicPaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpTopicPaths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.ResourceStuff.HelpTopicPaths", typeof(HelpTopicPaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Word_Lists/Phonetic_Sort_Options.htm.
        /// </summary>
        public static string hidAdvancedPhoneticSortOptions {
            get {
                return ResourceManager.GetString("hidAdvancedPhoneticSortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Ambiguous_Sequences/Ambiguous_Sequences_dialog_box.htm.
        /// </summary>
        public static string hidAmbiguousSequencesDlg {
            get {
                return ResourceManager.GetString("hidAmbiguousSequencesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Word_Lists/Phonetic_Sort_Options.htm.
        /// </summary>
        public static string hidBasicPhoneticSortOptions {
            get {
                return ResourceManager.GetString("hidBasicPhoneticSortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Classes/Classes_overview.htm.
        /// </summary>
        public static string hidClassesDlg {
            get {
                return ResourceManager.GetString("hidClassesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Consonant_and_Vowel_Charts/Consonant_and_Vowel_Chart_views.htm.
        /// </summary>
        public static string hidConsonantChartView {
            get {
                return ResourceManager.GetString("hidConsonantChartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/Custom_Fields.htm.
        /// </summary>
        public static string hidCustomFieldsDlg {
            get {
                return ResourceManager.GetString("hidCustomFieldsDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Options/CV_Patterns_tab_Options.htm.
        /// </summary>
        public static string hidCVPatternsOptions {
            get {
                return ResourceManager.GetString("hidCVPatternsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Data_Corpus/Data_Corpus_view.htm.
        /// </summary>
        public static string hidDataCorpusView {
            get {
                return ResourceManager.GetString("hidDataCorpusView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Classes/Descriptive_Features_Class.htm.
        /// </summary>
        public static string hidDescriptiveFeatureClassDlg {
            get {
                return ResourceManager.GetString("hidDescriptiveFeatureClassDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Descriptive_Features/Descriptive_Features_dialog_box.htm.
        /// </summary>
        public static string hidDescriptiveFeaturesDlg {
            get {
                return ResourceManager.GetString("hidDescriptiveFeaturesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Classes/Distinctive_Features_Class.htm.
        /// </summary>
        public static string hidDistinctiveFeatureClassDlg {
            get {
                return ResourceManager.GetString("hidDistinctiveFeatureClassDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Distinctive_Features/Distinctive_Features_dialog_box.htm.
        /// </summary>
        public static string hidDistinctiveFeaturesDlg {
            get {
                return ResourceManager.GetString("hidDistinctiveFeaturesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Distribution_Charts/Distribution_Charts_view.htm.
        /// </summary>
        public static string hidDistributionChartsView {
            get {
                return ResourceManager.GetString("hidDistributionChartsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Word_Lists/Experimental_transcriptions_ScreenTip.htm.
        /// </summary>
        public static string hidExperimentalTranscriptionsPopup {
            get {
                return ResourceManager.GetString("hidExperimentalTranscriptionsPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Filters/Filters_dialog_box.htm.
        /// </summary>
        public static string hidFiltersDlg {
            get {
                return ResourceManager.GetString("hidFiltersDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Edit/Find.htm.
        /// </summary>
        public static string hidFindDlg {
            get {
                return ResourceManager.GetString("hidFindDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Options/Fonts_tab_Options.htm.
        /// </summary>
        public static string hidFontsOptions {
            get {
                return ResourceManager.GetString("hidFontsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/FieldWorks_Data_Source_Properties.htm.
        /// </summary>
        public static string hidFw7DataSourcePropertiesDlg {
            get {
                return ResourceManager.GetString("hidFw7DataSourcePropertiesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/FieldWorks_Data_Source_Properties.htm.
        /// </summary>
        public static string hidFwDataSourcePropertiesDlg {
            get {
                return ResourceManager.GetString("hidFwDataSourcePropertiesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/FieldWorks_Projects.htm.
        /// </summary>
        public static string hidFwProjectsDlg {
            get {
                return ResourceManager.GetString("hidFwProjectsDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview/Getting_started.htm.
        /// </summary>
        public static string hidGettingStarted {
            get {
                return ResourceManager.GetString("hidGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA Exercises.doc.
        /// </summary>
        public static string hidHelpTrainingExercisesDoc {
            get {
                return ResourceManager.GetString("hidHelpTrainingExercisesDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA Instructor Guide.doc.
        /// </summary>
        public static string hidHelpTrainingInstructorGuideDoc {
            get {
                return ResourceManager.GetString("hidHelpTrainingInstructorGuideDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA Student Manual.doc.
        /// </summary>
        public static string hidHelpTrainingStudentManualDoc {
            get {
                return ResourceManager.GetString("hidHelpTrainingStudentManualDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Consonant_and_Vowel_Charts/Ignored_Suprasegmentals.htm.
        /// </summary>
        public static string hidIgnoredSuprasegmentalsPopup {
            get {
                return ResourceManager.GetString("hidIgnoredSuprasegmentalsPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Result_Tab_Groups/Minimal_Pairs_Options.htm.
        /// </summary>
        public static string hidMinimalPairsOptions {
            get {
                return ResourceManager.GetString("hidMinimalPairsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/Data_Source_Missing.htm.
        /// </summary>
        public static string hidMissingDataSourceMsgBox {
            get {
                return ResourceManager.GetString("hidMissingDataSourceMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/FieldWorks_Database_Missing.htm.
        /// </summary>
        public static string hidMissingFWDatabaseMsgBox {
            get {
                return ResourceManager.GetString("hidMissingFWDatabaseMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/New_Project_Settings.htm.
        /// </summary>
        public static string hidNewProjectSettingsDlg {
            get {
                return ResourceManager.GetString("hidNewProjectSettingsDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Classes/Phones_Class.htm.
        /// </summary>
        public static string hidPhoneticCharacterClassDlg {
            get {
                return ResourceManager.GetString("hidPhoneticCharacterClassDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/Project_Settings.htm.
        /// </summary>
        public static string hidProjectSettingsDlg {
            get {
                return ResourceManager.GetString("hidProjectSettingsDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Options/Record_View_tab_Options.htm.
        /// </summary>
        public static string hidRecordViewOptions {
            get {
                return ResourceManager.GetString("hidRecordViewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/Export/Export_to_Rich_Text_Format_RTF.htm.
        /// </summary>
        public static string hidRtfExportDlg {
            get {
                return ResourceManager.GetString("hidRtfExportDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Distribution_Charts/Save_Distribution_Chart.htm.
        /// </summary>
        public static string hidSaveDistributionChartDlg {
            get {
                return ResourceManager.GetString("hidSaveDistributionChartDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Search/Save_Search_Pattern.htm.
        /// </summary>
        public static string hidSaveSearchQueryDlg {
            get {
                return ResourceManager.GetString("hidSaveSearchQueryDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Search_Options.htm.
        /// </summary>
        public static string hidSearchOptionsDistributionChartsView {
            get {
                return ResourceManager.GetString("hidSearchOptionsDistributionChartsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Search_Options.htm.
        /// </summary>
        public static string hidSearchOptionsOnFilters {
            get {
                return ResourceManager.GetString("hidSearchOptionsOnFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Search/Search_Options_Search_View.htm.
        /// </summary>
        public static string hidSearchOptionsSearchView {
            get {
                return ResourceManager.GetString("hidSearchOptionsSearchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/AND_groups.htm.
        /// </summary>
        public static string hidSearchPatternsAndGroups {
            get {
                return ResourceManager.GetString("hidSearchPatternsAndGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/Diacritic_placeholders.htm.
        /// </summary>
        public static string hidSearchPatternsDiacriticPlaceholders {
            get {
                return ResourceManager.GetString("hidSearchPatternsDiacriticPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/Examples_of_search_pattern_elements.htm.
        /// </summary>
        public static string hidSearchPatternsExamples {
            get {
                return ResourceManager.GetString("hidSearchPatternsExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/One_or_more_phones_or_diacritics.htm.
        /// </summary>
        public static string hidSearchPatternsOneOrMore {
            get {
                return ResourceManager.GetString("hidSearchPatternsOneOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/OR_groups.htm.
        /// </summary>
        public static string hidSearchPatternsOrGroups {
            get {
                return ResourceManager.GetString("hidSearchPatternsOrGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/Search_Patterns_overview.htm.
        /// </summary>
        public static string hidSearchPatternsOverview {
            get {
                return ResourceManager.GetString("hidSearchPatternsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/Space_or_word_boundary.htm.
        /// </summary>
        public static string hidSearchPatternsSpaceOrWrdBoundary {
            get {
                return ResourceManager.GetString("hidSearchPatternsSpaceOrWrdBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/Troubleshooting_incorrect_search_results.htm.
        /// </summary>
        public static string hidSearchPatternsTroubleshooting {
            get {
                return ResourceManager.GetString("hidSearchPatternsTroubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search_Patterns/Zero_or_more_phones_or_diacritics.htm.
        /// </summary>
        public static string hidSearchPatternsZeroOrMore {
            get {
                return ResourceManager.GetString("hidSearchPatternsZeroOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Search/Search_view.htm.
        /// </summary>
        public static string hidSearchView {
            get {
                return ResourceManager.GetString("hidSearchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/Standard_Format_Data_Source_Properties.htm.
        /// </summary>
        public static string hidSFDataSourcePropertiesDlg {
            get {
                return ResourceManager.GetString("hidSFDataSourcePropertiesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/View/Similar_Environments_Options.htm.
        /// </summary>
        public static string hidSimilarEnvironmentsOptions {
            get {
                return ResourceManager.GetString("hidSimilarEnvironmentsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Options/Sorting_tab_Options.htm.
        /// </summary>
        public static string hidSortingOptions {
            get {
                return ResourceManager.GetString("hidSortingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help_topic_does_not_exist.htm.
        /// </summary>
        public static string hidTopicDoesNotExist {
            get {
                return ResourceManager.GetString("hidTopicDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/File/Transcription_Encoding_Converters.htm.
        /// </summary>
        public static string hidTransConvertersDlg {
            get {
                return ResourceManager.GetString("hidTransConvertersDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Transcription_Changes_dialog_box/Transcription_Changes_dialog_box.htm.
        /// </summary>
        public static string hidTranscriptionChangesDlg {
            get {
                return ResourceManager.GetString("hidTranscriptionChangesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic_Transcriptions/Troubleshooting_undefined_phonetic_characters.htm.
        /// </summary>
        public static string hidTroubleshootingUndefinedPhoneticCharacters {
            get {
                return ResourceManager.GetString("hidTroubleshootingUndefinedPhoneticCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Word_Lists/Uncertain_phones_ScreenTip.htm.
        /// </summary>
        public static string hidUncertainPhonesPopup {
            get {
                return ResourceManager.GetString("hidUncertainPhonesPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Classes/Undefined_Characters_in_Class.htm.
        /// </summary>
        public static string hidUndefinedCharactersInClassDlg {
            get {
                return ResourceManager.GetString("hidUndefinedCharactersInClassDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Undefined_Phonetic_Characters.htm.
        /// </summary>
        public static string hidUndefinedPhoneticCharactersDlg {
            get {
                return ResourceManager.GetString("hidUndefinedPhoneticCharactersDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Options/User_Interface_tab_Options.htm.
        /// </summary>
        public static string hidUserInterfaceOptionsPage {
            get {
                return ResourceManager.GetString("hidUserInterfaceOptionsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Views/Consonant_and_Vowel_Charts/Consonant_and_Vowel_Chart_views.htm.
        /// </summary>
        public static string hidVowelChartView {
            get {
                return ResourceManager.GetString("hidVowelChartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Interface/Menus/Tools/Options/Word_Lists_tab_Options.htm.
        /// </summary>
        public static string hidWordListOptions {
            get {
                return ResourceManager.GetString("hidWordListOptions", resourceCulture);
            }
        }
    }
}
