//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.ResourceStuff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaTMStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaTMStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.ResourceStuff.PaTMStrings", typeof(PaTMStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Category.
        /// </summary>
        public static string kstidAddCategoryText {
            get {
                return ResourceManager.GetString("kstidAddCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string kstidAddCategoryToolTip {
            get {
                return ResourceManager.GetString("kstidAddCategoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        public static string kstidAddFeaturesText {
            get {
                return ResourceManager.GetString("kstidAddFeaturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new custom feature.
        /// </summary>
        public static string kstidAddFeaturesToolTip {
            get {
                return ResourceManager.GetString("kstidAddFeaturesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Folder.
        /// </summary>
        public static string kstidAddFolderText {
            get {
                return ResourceManager.GetString("kstidAddFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string kstidAddFolderToolTip {
            get {
                return ResourceManager.GetString("kstidAddFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string kstidAddSavedPatternCategoryText {
            get {
                return ResourceManager.GetString("kstidAddSavedPatternCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Saved Pattern Category.
        /// </summary>
        public static string kstidAddSavedPatternCategoryToolTip {
            get {
                return ResourceManager.GetString("kstidAddSavedPatternCategoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        public static string kstidAddText {
            get {
                return ResourceManager.GetString("kstidAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback &amp;Speed.
        /// </summary>
        public static string kstidAdjustPlaybackSpeedParentText {
            get {
                return ResourceManager.GetString("kstidAdjustPlaybackSpeedParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback &amp;Speed.
        /// </summary>
        public static string kstidAdjustPlaybackSpeedText {
            get {
                return ResourceManager.GetString("kstidAdjustPlaybackSpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Speed.
        /// </summary>
        public static string kstidAdjustPlaybackSpeedToolTip {
            get {
                return ResourceManager.GetString("kstidAdjustPlaybackSpeedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ambiguous Items....
        /// </summary>
        public static string kstidAmbiguousItemsText {
            get {
                return ResourceManager.GetString("kstidAmbiguousItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ambiguous Sequences....
        /// </summary>
        public static string kstidAmbiguousSequencesText {
            get {
                return ResourceManager.GetString("kstidAmbiguousSequencesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup....
        /// </summary>
        public static string kstidBackupProjectText {
            get {
                return ResourceManager.GetString("kstidBackupProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup &amp;&amp; Restore.
        /// </summary>
        public static string kstidBackupRestoreText {
            get {
                return ResourceManager.GetString("kstidBackupRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string kstidBeginSearchText {
            get {
                return ResourceManager.GetString("kstidBeginSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string kstidBeginSearchToolTip {
            get {
                return ResourceManager.GetString("kstidBeginSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Build Processing List....
        /// </summary>
        public static string kstidBuildProcListText {
            get {
                return ResourceManager.GetString("kstidBuildProcListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cascade.
        /// </summary>
        public static string kstidCascadeText {
            get {
                return ResourceManager.GetString("kstidCascadeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascade Windows.
        /// </summary>
        public static string kstidCascadeToolTip {
            get {
                return ResourceManager.GetString("kstidCascadeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is &amp;Alone.
        /// </summary>
        public static string kstidCharAloneText {
            get {
                return ResourceManager.GetString("kstidCharAloneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word List for Alone Character.
        /// </summary>
        public static string kstidCharAloneToolTip {
            get {
                return ResourceManager.GetString("kstidCharAloneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is Any&amp;where.
        /// </summary>
        public static string kstidCharAnywhereText {
            get {
                return ResourceManager.GetString("kstidCharAnywhereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word List for Anywhere Character.
        /// </summary>
        public static string kstidCharAnywhereToolTip {
            get {
                return ResourceManager.GetString("kstidCharAnywhereToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character D&amp;uration Graph.
        /// </summary>
        public static string kstidCharDurationGraphText {
            get {
                return ResourceManager.GetString("kstidCharDurationGraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Duration Graph.
        /// </summary>
        public static string kstidCharDurationGraphToolTip {
            get {
                return ResourceManager.GetString("kstidCharDurationGraphToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is &amp;Final.
        /// </summary>
        public static string kstidCharFinalText {
            get {
                return ResourceManager.GetString("kstidCharFinalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word List for Final Character.
        /// </summary>
        public static string kstidCharFinalToolTip {
            get {
                return ResourceManager.GetString("kstidCharFinalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is &amp;Initial.
        /// </summary>
        public static string kstidCharInitialText {
            get {
                return ResourceManager.GetString("kstidCharInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word List for Initial Character.
        /// </summary>
        public static string kstidCharInitialToolTip {
            get {
                return ResourceManager.GetString("kstidCharInitialToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word List for Medial Character.
        /// </summary>
        public static string kstidCharMedialText {
            get {
                return ResourceManager.GetString("kstidCharMedialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Classes....
        /// </summary>
        public static string kstidClassesText {
            get {
                return ResourceManager.GetString("kstidClassesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string kstidClassesToolTip {
            get {
                return ResourceManager.GetString("kstidClassesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        public static string kstidClearChartText {
            get {
                return ResourceManager.GetString("kstidClearChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Chart.
        /// </summary>
        public static string kstidClearChartToolTip {
            get {
                return ResourceManager.GetString("kstidClearChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        public static string kstidClearPatternText {
            get {
                return ResourceManager.GetString("kstidClearPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Current Search Pattern and Results.
        /// </summary>
        public static string kstidClearPatternToolTip {
            get {
                return ResourceManager.GetString("kstidClearPatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear &amp;List.
        /// </summary>
        public static string kstidClearRecentPatternListText {
            get {
                return ResourceManager.GetString("kstidClearRecentPatternListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        public static string kstidClearRecentPatternListToolTip {
            get {
                return ResourceManager.GetString("kstidClearRecentPatternListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string kstidCloseActiveWindowText {
            get {
                return ResourceManager.GetString("kstidCloseActiveWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Active Window.
        /// </summary>
        public static string kstidCloseActiveWindowToolTip {
            get {
                return ResourceManager.GetString("kstidCloseActiveWindowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Tab Groups.
        /// </summary>
        public static string kstidCloseAllTabGroupsText {
            get {
                return ResourceManager.GetString("kstidCloseAllTabGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab Group.
        /// </summary>
        public static string kstidCloseTabGroupText {
            get {
                return ResourceManager.GetString("kstidCloseTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        public static string kstidCloseTabText {
            get {
                return ResourceManager.GetString("kstidCloseTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ollapse All Groups.
        /// </summary>
        public static string kstidCollapseAllGroupsText {
            get {
                return ResourceManager.GetString("kstidCollapseAllGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All Groups.
        /// </summary>
        public static string kstidCollapseAllGroupsToolTip {
            get {
                return ResourceManager.GetString("kstidCollapseAllGroupsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Compact Database on Close.
        /// </summary>
        public static string kstidCompactDBText {
            get {
                return ResourceManager.GetString("kstidCompactDBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Consonant Chart.
        /// </summary>
        public static string kstidConsonantChartText {
            get {
                return ResourceManager.GetString("kstidConsonantChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consonant Chart View (Ctrl+Alt+C).
        /// </summary>
        public static string kstidConsonantChartToolTip {
            get {
                return ResourceManager.GetString("kstidConsonantChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contents &amp;Pane by Filter.
        /// </summary>
        public static string kstidContentsByFilterText {
            get {
                return ResourceManager.GetString("kstidContentsByFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contents Pane by Filter.
        /// </summary>
        public static string kstidContentsByFilterToolTip {
            get {
                return ResourceManager.GetString("kstidContentsByFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Contents.
        /// </summary>
        public static string kstidContentsText {
            get {
                return ResourceManager.GetString("kstidContentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Contents.
        /// </summary>
        public static string kstidContentsToolTip {
            get {
                return ResourceManager.GetString("kstidContentsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string kstidCopySavedPatternText {
            get {
                return ResourceManager.GetString("kstidCopySavedPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Saved pattern.
        /// </summary>
        public static string kstidCopySavedPatternToolTip {
            get {
                return ResourceManager.GetString("kstidCopySavedPatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;opy Selected Pattern to Current Search Pattern.
        /// </summary>
        public static string kstidCopyToCurrentPatternText {
            get {
                return ResourceManager.GetString("kstidCopyToCurrentPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string kstidCurrentTabGroupText {
            get {
                return ResourceManager.GetString("kstidCurrentTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        public static string kstidCutSavedPatternText {
            get {
                return ResourceManager.GetString("kstidCutSavedPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut saved pattern.
        /// </summary>
        public static string kstidCutSavedPatternToolTip {
            get {
                return ResourceManager.GetString("kstidCutSavedPatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Data Corpus.
        /// </summary>
        public static string kstidDataCorpusText {
            get {
                return ResourceManager.GetString("kstidDataCorpusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Corpus View (Ctrl+Alt+D).
        /// </summary>
        public static string kstidDataCorpusToolTip {
            get {
                return ResourceManager.GetString("kstidDataCorpusToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Articulatory Features....
        /// </summary>
        public static string kstidDefineAFText {
            get {
                return ResourceManager.GetString("kstidDefineAFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Articulatory Features.
        /// </summary>
        public static string kstidDefineAFToolTip {
            get {
                return ResourceManager.GetString("kstidDefineAFToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Binary Features....
        /// </summary>
        public static string kstidDefineBFText {
            get {
                return ResourceManager.GetString("kstidDefineBFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Binary Features.
        /// </summary>
        public static string kstidDefineBFToolTip {
            get {
                return ResourceManager.GetString("kstidDefineBFToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;escriptive Features....
        /// </summary>
        public static string kstidDescriptiveFeaturesText {
            get {
                return ResourceManager.GetString("kstidDescriptiveFeaturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Diacritic Chart....
        /// </summary>
        public static string kstidDiacriticChartText {
            get {
                return ResourceManager.GetString("kstidDiacriticChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diacritic Chart.
        /// </summary>
        public static string kstidDiacriticChartToolTip {
            get {
                return ResourceManager.GetString("kstidDiacriticChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;istinctive Features....
        /// </summary>
        public static string kstidDistinctiveFeaturesText {
            get {
                return ResourceManager.GetString("kstidDistinctiveFeaturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock View.
        /// </summary>
        public static string kstidDockViewText {
            get {
                return ResourceManager.GetString("kstidDockViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock View.
        /// </summary>
        public static string kstidDockViewToolTip {
            get {
                return ResourceManager.GetString("kstidDockViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string kstidDoNothingToolTip {
            get {
                return ResourceManager.GetString("kstidDoNothingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Document.
        /// </summary>
        public static string kstidEditAudioDocText {
            get {
                return ResourceManager.GetString("kstidEditAudioDocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the Audio Document.
        /// </summary>
        public static string kstidEditAudioDocToolTip {
            get {
                return ResourceManager.GetString("kstidEditAudioDocToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string kstidEditCategory {
            get {
                return ResourceManager.GetString("kstidEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string kstidEditFeaturesText {
            get {
                return ResourceManager.GetString("kstidEditFeaturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Source Record.
        /// </summary>
        public static string kstidEditSourceRecordText {
            get {
                return ResourceManager.GetString("kstidEditSourceRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit source record.
        /// </summary>
        public static string kstidEditSourceRecordToolTip {
            get {
                return ResourceManager.GetString("kstidEditSourceRecordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string kstidEditText {
            get {
                return ResourceManager.GetString("kstidEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exercises....
        /// </summary>
        public static string kstidExercisesText {
            get {
                return ResourceManager.GetString("kstidExercisesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        public static string kstidExercisesToolTip {
            get {
                return ResourceManager.GetString("kstidExercisesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string kstidExitText {
            get {
                return ResourceManager.GetString("kstidExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Phonology Assistant.
        /// </summary>
        public static string kstidExitToolTip {
            get {
                return ResourceManager.GetString("kstidExitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Expand All Groups.
        /// </summary>
        public static string kstidExpandAllGroupsText {
            get {
                return ResourceManager.GetString("kstidExpandAllGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All Groups.
        /// </summary>
        public static string kstidExpandAllGroupsToolTip {
            get {
                return ResourceManager.GetString("kstidExpandAllGroupsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Transcription Changes....
        /// </summary>
        public static string kstidExperimentalTranscriptionsText {
            get {
                return ResourceManager.GetString("kstidExperimentalTranscriptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;HTML....
        /// </summary>
        public static string kstidExportAsHTMLText {
            get {
                return ResourceManager.GetString("kstidExportAsHTMLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to HTML File.
        /// </summary>
        public static string kstidExportAsHTMLToolTip {
            get {
                return ResourceManager.GetString("kstidExportAsHTMLToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &amp;XML....
        /// </summary>
        public static string kstidExportAsPAXMLText {
            get {
                return ResourceManager.GetString("kstidExportAsPAXMLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rich Text Format (RTF)....
        /// </summary>
        public static string kstidExportAsRTFText {
            get {
                return ResourceManager.GetString("kstidExportAsRTFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to RTF File.
        /// </summary>
        public static string kstidExportAsRTFToolTip {
            get {
                return ResourceManager.GetString("kstidExportAsRTFToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        public static string kstidExportAsText {
            get {
                return ResourceManager.GetString("kstidExportAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string kstidExportAsToolTip {
            get {
                return ResourceManager.GetString("kstidExportAsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Word 2003 XML....
        /// </summary>
        public static string kstidExportAsWordXmlText {
            get {
                return ResourceManager.GetString("kstidExportAsWordXmlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X&amp;LingPaper....
        /// </summary>
        public static string kstidExportAsXLingPaperText {
            get {
                return ResourceManager.GetString("kstidExportAsXLingPaperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XLingPaper File.
        /// </summary>
        public static string kstidExportAsXLingPaperToolTip {
            get {
                return ResourceManager.GetString("kstidExportAsXLingPaperToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string kstidFileCategory {
            get {
                return ResourceManager.GetString("kstidFileCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string kstidFileText {
            get {
                return ResourceManager.GetString("kstidFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi&amp;ll Chart.
        /// </summary>
        public static string kstidFillInChartText {
            get {
                return ResourceManager.GetString("kstidFillInChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Chart with Results.
        /// </summary>
        public static string kstidFillInChartToolTip {
            get {
                return ResourceManager.GetString("kstidFillInChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string kstidFiltersParentToolTip {
            get {
                return ResourceManager.GetString("kstidFiltersParentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filters....
        /// </summary>
        public static string kstidFiltersText {
            get {
                return ResourceManager.GetString("kstidFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp;Next.
        /// </summary>
        public static string kstidFindNextText {
            get {
                return ResourceManager.GetString("kstidFindNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string kstidFindNextToolTip {
            get {
                return ResourceManager.GetString("kstidFindNextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string kstidFindPhonesText {
            get {
                return ResourceManager.GetString("kstidFindPhonesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search View (Ctrl+Alt+S).
        /// </summary>
        public static string kstidFindPhonesToolTip {
            get {
                return ResourceManager.GetString("kstidFindPhonesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp;Previous.
        /// </summary>
        public static string kstidFindPreviousText {
            get {
                return ResourceManager.GetString("kstidFindPreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find previous.
        /// </summary>
        public static string kstidFindPreviousToolTip {
            get {
                return ResourceManager.GetString("kstidFindPreviousToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find.
        /// </summary>
        public static string kstidFindText {
            get {
                return ResourceManager.GetString("kstidFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string kstidFindToolTip {
            get {
                return ResourceManager.GetString("kstidFindToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal &amp;and Vertical Grid Lines.
        /// </summary>
        public static string kstidGridLinesBothText {
            get {
                return ResourceManager.GetString("kstidGridLinesBothText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal and Vertical Grid Lines.
        /// </summary>
        public static string kstidGridLinesBothToolTip {
            get {
                return ResourceManager.GetString("kstidGridLinesBothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Horizontal Grid Lines.
        /// </summary>
        public static string kstidGridLinesHorizontalText {
            get {
                return ResourceManager.GetString("kstidGridLinesHorizontalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Grid Lines.
        /// </summary>
        public static string kstidGridLinesHorizontalToolTip {
            get {
                return ResourceManager.GetString("kstidGridLinesHorizontalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No Grid Lines.
        /// </summary>
        public static string kstidGridLinesNoneText {
            get {
                return ResourceManager.GetString("kstidGridLinesNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Grid Lines.
        /// </summary>
        public static string kstidGridLinesNoneToolTip {
            get {
                return ResourceManager.GetString("kstidGridLinesNoneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vertical Grid Lines.
        /// </summary>
        public static string kstidGridLinesVerticalText {
            get {
                return ResourceManager.GetString("kstidGridLinesVerticalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Grid Lines.
        /// </summary>
        public static string kstidGridLinesVerticalToolTip {
            get {
                return ResourceManager.GetString("kstidGridLinesVerticalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Group by Field.
        /// </summary>
        public static string kstidGroupByFieldParentText {
            get {
                return ResourceManager.GetString("kstidGroupByFieldParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Field.
        /// </summary>
        public static string kstidGroupByFieldParentToolTip {
            get {
                return ResourceManager.GetString("kstidGroupByFieldParentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Group by Primary Sort Field.
        /// </summary>
        public static string kstidGroupBySortedFieldText {
            get {
                return ResourceManager.GetString("kstidGroupBySortedFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by Primary Sort Field.
        /// </summary>
        public static string kstidGroupBySortedFieldToolTip {
            get {
                return ResourceManager.GetString("kstidGroupBySortedFieldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About Phonology Assistant....
        /// </summary>
        public static string kstidHelpAboutText {
            get {
                return ResourceManager.GetString("kstidHelpAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Phonolgy Assistant....
        /// </summary>
        public static string kstidHelpAboutToolTip {
            get {
                return ResourceManager.GetString("kstidHelpAboutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string kstidHelpCategory {
            get {
                return ResourceManager.GetString("kstidHelpCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonology Assistant....
        /// </summary>
        public static string kstidHelpPAText {
            get {
                return ResourceManager.GetString("kstidHelpPAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonology Assistant Help.
        /// </summary>
        public static string kstidHelpPAToolTip {
            get {
                return ResourceManager.GetString("kstidHelpPAToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string kstidHelpText {
            get {
                return ResourceManager.GetString("kstidHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Training.
        /// </summary>
        public static string kstidHelpTrainingText {
            get {
                return ResourceManager.GetString("kstidHelpTrainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string kstidHelpTrainingToolTip {
            get {
                return ResourceManager.GetString("kstidHelpTrainingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogra&amp;m.
        /// </summary>
        public static string kstidHistogramText {
            get {
                return ResourceManager.GetString("kstidHistogramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string kstidHistogramToolTip {
            get {
                return ResourceManager.GetString("kstidHistogramToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  ] A&amp;ND Group.
        /// </summary>
        public static string kstidInsertANDGroupText {
            get {
                return ResourceManager.GetString("kstidInsertANDGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C] Any &amp;Consonant.
        /// </summary>
        public static string kstidInsertConsonantText {
            get {
                return ResourceManager.GetString("kstidInsertConsonantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Diacritic Placeholder.
        /// </summary>
        public static string kstidInsertDiacriticPlaceholderText {
            get {
                return ResourceManager.GetString("kstidInsertDiacriticPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        public static string kstidInsertIntoChartText {
            get {
                return ResourceManager.GetString("kstidInsertIntoChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Element into Current Chart Cell.
        /// </summary>
        public static string kstidInsertIntoChartToolTip {
            get {
                return ResourceManager.GetString("kstidInsertIntoChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        public static string kstidInsertIntoPatternText {
            get {
                return ResourceManager.GetString("kstidInsertIntoPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Element into Current Search Pattern.
        /// </summary>
        public static string kstidInsertIntoPatternToolTip {
            get {
                return ResourceManager.GetString("kstidInsertIntoPatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + &amp;One or More Phones or Diacritics.
        /// </summary>
        public static string kstidInsertOneOrMoreText {
            get {
                return ResourceManager.GetString("kstidInsertOneOrMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {  } O&amp;R Group.
        /// </summary>
        public static string kstidInsertORGroupText {
            get {
                return ResourceManager.GetString("kstidInsertORGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . &amp;Syllable Boundary.
        /// </summary>
        public static string kstidInsertSyllableBoundaryText {
            get {
                return ResourceManager.GetString("kstidInsertSyllableBoundaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [V] Any &amp;Vowel.
        /// </summary>
        public static string kstidInsertVowelText {
            get {
                return ResourceManager.GetString("kstidInsertVowelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Space/&amp;Word Boundary.
        /// </summary>
        public static string kstidInsertWordBoundaryText {
            get {
                return ResourceManager.GetString("kstidInsertWordBoundaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &amp;Zero or More Phones or Diacritics.
        /// </summary>
        public static string kstidInsertZeroOrMoreText {
            get {
                return ResourceManager.GetString("kstidInsertZeroOrMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Instructor Guide....
        /// </summary>
        public static string kstidInstructorGuideText {
            get {
                return ResourceManager.GetString("kstidInstructorGuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Guide.
        /// </summary>
        public static string kstidInstructorGuideToolTip {
            get {
                return ResourceManager.GetString("kstidInstructorGuideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Interlinear View....
        /// </summary>
        public static string kstidInterlinearViewText {
            get {
                return ResourceManager.GetString("kstidInterlinearViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlinear View.
        /// </summary>
        public static string kstidInterlinearViewToolTip {
            get {
                return ResourceManager.GetString("kstidInterlinearViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language Name....
        /// </summary>
        public static string kstidLangNameText {
            get {
                return ResourceManager.GetString("kstidLangNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Name.
        /// </summary>
        public static string kstidLangNameToolTip {
            get {
                return ResourceManager.GetString("kstidLangNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to New Side-&amp;By-Side Tab Group.
        /// </summary>
        public static string kstidMoveToNewSideBySideTabGroupText {
            get {
                return ResourceManager.GetString("kstidMoveToNewSideBySideTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to New Stac&amp;ked Tab Group.
        /// </summary>
        public static string kstidMoveToNewStackedTabGroupText {
            get {
                return ResourceManager.GetString("kstidMoveToNewStackedTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In &amp;Active Tab Group.
        /// </summary>
        public static string kstidNewTabInCurrentTabGroupText {
            get {
                return ResourceManager.GetString("kstidNewTabInCurrentTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Tab in Active Tab Group.
        /// </summary>
        public static string kstidNewTabInCurrentTabGroupToolTip {
            get {
                return ResourceManager.GetString("kstidNewTabInCurrentTabGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In New Side-&amp;By-Side Tab Group.
        /// </summary>
        public static string kstidNewTabInNewSideBySideTabGroupText {
            get {
                return ResourceManager.GetString("kstidNewTabInNewSideBySideTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tab in New Side-by-Side Tab Group.
        /// </summary>
        public static string kstidNewTabInNewSideBySideTabGroupToolTip {
            get {
                return ResourceManager.GetString("kstidNewTabInNewSideBySideTabGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In New Stac&amp;ked Tab Group.
        /// </summary>
        public static string kstidNewTabInNewStackedTabGroupText {
            get {
                return ResourceManager.GetString("kstidNewTabInNewStackedTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tab in New Stacked Tab Group.
        /// </summary>
        public static string kstidNewTabInNewStackedTabGroupToolTip {
            get {
                return ResourceManager.GetString("kstidNewTabInNewStackedTabGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Tab.
        /// </summary>
        public static string kstidNewTabText {
            get {
                return ResourceManager.GetString("kstidNewTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Results Tab.
        /// </summary>
        public static string kstidNewTabToolTip {
            get {
                return ResourceManager.GetString("kstidNewTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Project....
        /// </summary>
        public static string kstidNewText {
            get {
                return ResourceManager.GetString("kstidNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Project.
        /// </summary>
        public static string kstidNewToolTip {
            get {
                return ResourceManager.GetString("kstidNewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;No Filter).
        /// </summary>
        public static string kstidNoFilterText {
            get {
                return ResourceManager.GetString("kstidNoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Project....
        /// </summary>
        public static string kstidOpenText {
            get {
                return ResourceManager.GetString("kstidOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string kstidOpenToolTip {
            get {
                return ResourceManager.GetString("kstidOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        public static string kstidOptionsText {
            get {
                return ResourceManager.GetString("kstidOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string kstidOptionsToolTip {
            get {
                return ResourceManager.GetString("kstidOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string kstidPasteSavedPatternText {
            get {
                return ResourceManager.GetString("kstidPasteSavedPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Saved Pattern.
        /// </summary>
        public static string kstidPasteSavedPatternToolTip {
            get {
                return ResourceManager.GetString("kstidPasteSavedPatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Phone Inventory.
        /// </summary>
        public static string kstidPhoneInventoryText {
            get {
                return ResourceManager.GetString("kstidPhoneInventoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Inventory.
        /// </summary>
        public static string kstidPhoneInventoryToolTip {
            get {
                return ResourceManager.GetString("kstidPhoneInventoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Sort Options.
        /// </summary>
        public static string kstidPhoneticSortText {
            get {
                return ResourceManager.GetString("kstidPhoneticSortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Sort Options.
        /// </summary>
        public static string kstidPhoneticSortToolTip {
            get {
                return ResourceManager.GetString("kstidPhoneticSortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Playback.
        /// </summary>
        public static string kstidPlaybackOnMenuText {
            get {
                return ResourceManager.GetString("kstidPlaybackOnMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string kstidPlaybackOnMenuToolTip {
            get {
                return ResourceManager.GetString("kstidPlaybackOnMenuToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback &amp;Repeatedly.
        /// </summary>
        public static string kstidPlaybackRepeatedlyText {
            get {
                return ResourceManager.GetString("kstidPlaybackRepeatedlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Repeatedly.
        /// </summary>
        public static string kstidPlaybackRepeatedlyToolTip {
            get {
                return ResourceManager.GetString("kstidPlaybackRepeatedlyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback &amp;Repeatedly.
        /// </summary>
        public static string kstidPlaybackRepeatText {
            get {
                return ResourceManager.GetString("kstidPlaybackRepeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Repeatedly.
        /// </summary>
        public static string kstidPlaybackRepeatToolTip {
            get {
                return ResourceManager.GetString("kstidPlaybackRepeatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Playback.
        /// </summary>
        public static string kstidPlaybackText {
            get {
                return ResourceManager.GetString("kstidPlaybackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string kstidPlaybackToolTip {
            get {
                return ResourceManager.GetString("kstidPlaybackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &amp;Management.
        /// </summary>
        public static string kstidProjectManagementText {
            get {
                return ResourceManager.GetString("kstidProjectManagementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;roject Settings....
        /// </summary>
        public static string kstidProjectSettingsText {
            get {
                return ResourceManager.GetString("kstidProjectSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        public static string kstidRegExpressionSrchDlgText {
            get {
                return ResourceManager.GetString("kstidRegExpressionSrchDlgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression Search Dialog.
        /// </summary>
        public static string kstidRegExpressionSrchDlgToolTip {
            get {
                return ResourceManager.GetString("kstidRegExpressionSrchDlgToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reload Project Data Sources.
        /// </summary>
        public static string kstidReloadProjectText {
            get {
                return ResourceManager.GetString("kstidReloadProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        public static string kstidRemovePatternText {
            get {
                return ResourceManager.GetString("kstidRemovePatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Pattern.
        /// </summary>
        public static string kstidRemovePatternToolTip {
            get {
                return ResourceManager.GetString("kstidRemovePatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename.
        /// </summary>
        public static string kstidRenameText {
            get {
                return ResourceManager.GetString("kstidRenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Selection.
        /// </summary>
        public static string kstidRenameToolTip {
            get {
                return ResourceManager.GetString("kstidRenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore Defaults.
        /// </summary>
        public static string kstidRestoreDefaultsText {
            get {
                return ResourceManager.GetString("kstidRestoreDefaultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default feature names and character features.
        /// </summary>
        public static string kstidRestoreDefaultsToolTip {
            get {
                return ResourceManager.GetString("kstidRestoreDefaultsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore....
        /// </summary>
        public static string kstidRestoreProjectText {
            get {
                return ResourceManager.GetString("kstidRestoreProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As....
        /// </summary>
        public static string kstidSaveChartAsText {
            get {
                return ResourceManager.GetString("kstidSaveChartAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string kstidSaveChartOnMenuText {
            get {
                return ResourceManager.GetString("kstidSaveChartOnMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;ave.
        /// </summary>
        public static string kstidSaveChartText {
            get {
                return ResourceManager.GetString("kstidSaveChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Chart.
        /// </summary>
        public static string kstidSaveChartToolTip {
            get {
                return ResourceManager.GetString("kstidSaveChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As....
        /// </summary>
        public static string kstidSavePatternAsText {
            get {
                return ResourceManager.GetString("kstidSavePatternAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Search Pattern As....
        /// </summary>
        public static string kstidSavePatternAsToolTip {
            get {
                return ResourceManager.GetString("kstidSavePatternAsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string kstidSavePatternOnMenuText {
            get {
                return ResourceManager.GetString("kstidSavePatternOnMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Search Pattern.
        /// </summary>
        public static string kstidSavePatternOnMenuToolTip {
            get {
                return ResourceManager.GetString("kstidSavePatternOnMenuToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string kstidSavePatternText {
            get {
                return ResourceManager.GetString("kstidSavePatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Search Pattern.
        /// </summary>
        public static string kstidSavePatternToolTip {
            get {
                return ResourceManager.GetString("kstidSavePatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        public static string kstidSearchOptionsText {
            get {
                return ResourceManager.GetString("kstidSearchOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Options.
        /// </summary>
        public static string kstidSearchOptionsToolTip {
            get {
                return ResourceManager.GetString("kstidSearchOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search Using Selected Pattern.
        /// </summary>
        public static string kstidSearchUsingPatternText {
            get {
                return ResourceManager.GetString("kstidSearchUsingPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Columns.
        /// </summary>
        public static string kstidSetColumnVisibilityText {
            get {
                return ResourceManager.GetString("kstidSetColumnVisibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or Hide Columns.
        /// </summary>
        public static string kstidSetColumnVisibilityToolTip {
            get {
                return ResourceManager.GetString("kstidSetColumnVisibilityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;RTF Editor Location....
        /// </summary>
        public static string kstidSetDirRTFText {
            get {
                return ResourceManager.GetString("kstidSetDirRTFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set RTF Editor Location.
        /// </summary>
        public static string kstidSetDirRTFToolTip {
            get {
                return ResourceManager.GetString("kstidSetDirRTFToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Minimal Pairs.
        /// </summary>
        public static string kstidShowCIEResultsText {
            get {
                return ResourceManager.GetString("kstidShowCIEResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal Pairs.
        /// </summary>
        public static string kstidShowCIEResultsToolTip {
            get {
                return ResourceManager.GetString("kstidShowCIEResultsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid &amp;Columns.
        /// </summary>
        public static string kstidShowGridColumnsText {
            get {
                return ResourceManager.GetString("kstidShowGridColumnsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Columns.
        /// </summary>
        public static string kstidShowGridColumnsToolTip {
            get {
                return ResourceManager.GetString("kstidShowGridColumnsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid &amp;Lines.
        /// </summary>
        public static string kstidShowGridLinesText {
            get {
                return ResourceManager.GetString("kstidShowGridLinesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Lines.
        /// </summary>
        public static string kstidShowGridLinesToolTip {
            get {
                return ResourceManager.GetString("kstidShowGridLinesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Record View.
        /// </summary>
        public static string kstidShowRecordPaneText {
            get {
                return ResourceManager.GetString("kstidShowRecordPaneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record View.
        /// </summary>
        public static string kstidShowRecordPaneToolTip {
            get {
                return ResourceManager.GetString("kstidShowRecordPaneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in &amp;Active Tab Group.
        /// </summary>
        public static string kstidShowResultsInCurrentTabGroupText {
            get {
                return ResourceManager.GetString("kstidShowResultsInCurrentTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results in active tab group.
        /// </summary>
        public static string kstidShowResultsInCurrentTabGroupToolTip {
            get {
                return ResourceManager.GetString("kstidShowResultsInCurrentTabGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in New Side-by-Side Tab group.
        /// </summary>
        public static string kstidShowResultsInInNewSideBySideTabGroupToolTip {
            get {
                return ResourceManager.GetString("kstidShowResultsInInNewSideBySideTabGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in New Side-&amp;By-Side Tab Group.
        /// </summary>
        public static string kstidShowResultsInNewSideBySideTabGroupText {
            get {
                return ResourceManager.GetString("kstidShowResultsInNewSideBySideTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in New Stac&amp;ked Tab Group.
        /// </summary>
        public static string kstidShowResultsInNewStackedTabGroupText {
            get {
                return ResourceManager.GetString("kstidShowResultsInNewStackedTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in New Stacked Tab Group.
        /// </summary>
        public static string kstidShowResultsInNewStackedTabGroupToolTip {
            get {
                return ResourceManager.GetString("kstidShowResultsInNewStackedTabGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show Results.
        /// </summary>
        public static string kstidShowResultsText {
            get {
                return ResourceManager.GetString("kstidShowResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Search Results.
        /// </summary>
        public static string kstidShowResultsToolTip {
            get {
                return ResourceManager.GetString("kstidShowResultsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string kstidShowSearchResultsText {
            get {
                return ResourceManager.GetString("kstidShowSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search using chart&apos;s current item and environment.
        /// </summary>
        public static string kstidShowSearchResultsToolTip {
            get {
                return ResourceManager.GetString("kstidShowSearchResultsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status &amp;Bar.
        /// </summary>
        public static string kstidShowStatusBarText {
            get {
                return ResourceManager.GetString("kstidShowStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status Bar.
        /// </summary>
        public static string kstidShowStatusBarToolTip {
            get {
                return ResourceManager.GetString("kstidShowStatusBarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Alphabetically.
        /// </summary>
        public static string kstidSortAlphaText {
            get {
                return ResourceManager.GetString("kstidSortAlphaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Character Type.
        /// </summary>
        public static string kstidSortCharTypeText {
            get {
                return ResourceManager.GetString("kstidSortCharTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unicode (e.g. A-Z).
        /// </summary>
        public static string kstidSortCodepointOrderText {
            get {
                return ResourceManager.GetString("kstidSortCodepointOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sort IPA Characters.
        /// </summary>
        public static string kstidSortIPACharsText {
            get {
                return ResourceManager.GetString("kstidSortIPACharsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort IPA Characters.
        /// </summary>
        public static string kstidSortIPACharsToolTip {
            get {
                return ResourceManager.GetString("kstidSortIPACharsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manner of Articulation.
        /// </summary>
        public static string kstidSortMOAOrderText {
            get {
                return ResourceManager.GetString("kstidSortMOAOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Place of Articulation.
        /// </summary>
        public static string kstidSortPOAOrderText {
            get {
                return ResourceManager.GetString("kstidSortPOAOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User-defined Order.
        /// </summary>
        public static string kstidSortUserDefinedOrderText {
            get {
                return ResourceManager.GetString("kstidSortUserDefinedOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop Playback.
        /// </summary>
        public static string kstidStopPlaybackText {
            get {
                return ResourceManager.GetString("kstidStopPlaybackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Playback.
        /// </summary>
        public static string kstidStopPlaybackToolTip {
            get {
                return ResourceManager.GetString("kstidStopPlaybackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Student Manual....
        /// </summary>
        public static string kstidStudentManualText {
            get {
                return ResourceManager.GetString("kstidStudentManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Manual.
        /// </summary>
        public static string kstidStudentManualToolTip {
            get {
                return ResourceManager.GetString("kstidStudentManualToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile &amp;Horizontally.
        /// </summary>
        public static string kstidTileHorzText {
            get {
                return ResourceManager.GetString("kstidTileHorzText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Windows Horizontally.
        /// </summary>
        public static string kstidTileHorzToolTip {
            get {
                return ResourceManager.GetString("kstidTileHorzToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile &amp;Vertically.
        /// </summary>
        public static string kstidTileVertText {
            get {
                return ResourceManager.GetString("kstidTileVertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Windows Vertically.
        /// </summary>
        public static string kstidTileVertToolTip {
            get {
                return ResourceManager.GetString("kstidTileVertToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string kstidToolsCategory {
            get {
                return ResourceManager.GetString("kstidToolsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string kstidToolsText {
            get {
                return ResourceManager.GetString("kstidToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undefined Phonetic Characters....
        /// </summary>
        public static string kstidUndefinedCharactersText {
            get {
                return ResourceManager.GetString("kstidUndefinedCharactersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undock View.
        /// </summary>
        public static string kstidUnDockViewText {
            get {
                return ResourceManager.GetString("kstidUnDockViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undock View.
        /// </summary>
        public static string kstidUnDockViewToolTip {
            get {
                return ResourceManager.GetString("kstidUnDockViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ve&amp;rify.
        /// </summary>
        public static string kstidVerifyPatternText {
            get {
                return ResourceManager.GetString("kstidVerifyPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify validity of current search pattern.
        /// </summary>
        public static string kstidVerifyPatternToolTip {
            get {
                return ResourceManager.GetString("kstidVerifyPatternToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string kstidViewCategory {
            get {
                return ResourceManager.GetString("kstidViewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        public static string kstidViewText {
            get {
                return ResourceManager.GetString("kstidViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vowel Chart.
        /// </summary>
        public static string kstidVowelChartText {
            get {
                return ResourceManager.GetString("kstidVowelChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vowel Chart View (Ctrl+Alt+V).
        /// </summary>
        public static string kstidVowelChartToolTip {
            get {
                return ResourceManager.GetString("kstidVowelChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string kstidWindowCategory {
            get {
                return ResourceManager.GetString("kstidWindowCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Default Field Information.
        /// </summary>
        public static string kstidWriteDefaultFieldInfoText {
            get {
                return ResourceManager.GetString("kstidWriteDefaultFieldInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write IPA Cache.
        /// </summary>
        public static string kstidWriteIPACacheText {
            get {
                return ResourceManager.GetString("kstidWriteIPACacheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        public static string kstidXYChartSearchOptionsText {
            get {
                return ResourceManager.GetString("kstidXYChartSearchOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Options for Current Chart Column.
        /// </summary>
        public static string kstidXYChartSearchOptionsToolTip {
            get {
                return ResourceManager.GetString("kstidXYChartSearchOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in &amp;Active Tab Group.
        /// </summary>
        public static string kstidXYChartShowResultsToCurrentTabGroupText {
            get {
                return ResourceManager.GetString("kstidXYChartShowResultsToCurrentTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in New Side-&amp;By-Side Tab Group.
        /// </summary>
        public static string kstidXYChartShowResultsToNewSideBySideTabGroupText {
            get {
                return ResourceManager.GetString("kstidXYChartShowResultsToNewSideBySideTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results in New Stac&amp;ked Tab Group.
        /// </summary>
        public static string kstidXYChartShowResultsToNewStackedTabGroupText {
            get {
                return ResourceManager.GetString("kstidXYChartShowResultsToNewStackedTabGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Distribution Charts.
        /// </summary>
        public static string kstidXYChartText {
            get {
                return ResourceManager.GetString("kstidXYChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Charts View (Ctrl+Alt+X).
        /// </summary>
        public static string kstidXYChartToolTip {
            get {
                return ResourceManager.GetString("kstidXYChartToolTip", resourceCulture);
            }
        }
    }
}
