//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.AddOn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.AddOn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap kimidBackup {
            get {
                object obj = ResourceManager.GetObject("kimidBackup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup complete..
        /// </summary>
        internal static string kstidBackupCompleteMsg {
            get {
                return ResourceManager.GetString("kstidBackupCompleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Backup ({1}).zip.
        /// </summary>
        internal static string kstidBackupFilenameFmt {
            get {
                return ResourceManager.GetString("kstidBackupFilenameFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup Project....
        /// </summary>
        internal static string kstidBackupMenuText {
            get {
                return ResourceManager.GetString("kstidBackupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup File to Create.
        /// </summary>
        internal static string kstidBackupOFDCaption {
            get {
                return ResourceManager.GetString("kstidBackupOFDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify folder in which to restore {0} data source file(s)..
        /// </summary>
        internal static string kstidBrowseForDataSourceFolderDesc {
            get {
                return ResourceManager.GetString("kstidBrowseForDataSourceFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify folder in which to restore {0} project files..
        /// </summary>
        internal static string kstidBrowseForPrjFolderDesc {
            get {
                return ResourceManager.GetString("kstidBrowseForPrjFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string kstidCloseButtonText {
            get {
                return ResourceManager.GetString("kstidCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP File (*.zip)|*.zip|All Files (*.*)|*.*.
        /// </summary>
        internal static string kstidFileTypesForOFD {
            get {
                return ResourceManager.GetString("kstidFileTypesForOFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore is complete. Would you\nlike to open the restored project?.
        /// </summary>
        internal static string kstidLoadPrjMsg {
            get {
                return ResourceManager.GetString("kstidLoadPrjMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified zip file does not appear to contain a Phonology Assistant project..
        /// </summary>
        internal static string kstidNoPrjInZipFileMsg {
            get {
                return ResourceManager.GetString("kstidNoPrjInZipFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a project file by the name of &apos;{0}&apos; in the specified restore\nfolder. Do you want to overwrite the existing project files? If you answer &apos;Yes&apos;\nthen data source files that may already exist will also be overwritten..
        /// </summary>
        internal static string kstidPrjAlreadyInFolderMsg {
            get {
                return ResourceManager.GetString("kstidPrjAlreadyInFolderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data sources in the project..
        /// </summary>
        internal static string kstidPrjIsEmptyMsg {
            get {
                return ResourceManager.GetString("kstidPrjIsEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading backup file....
        /// </summary>
        internal static string kstidReadingBackupFileMsg {
            get {
                return ResourceManager.GetString("kstidReadingBackupFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res&amp;tore a Project....
        /// </summary>
        internal static string kstidRestoreMenuText {
            get {
                return ResourceManager.GetString("kstidRestoreMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to Restore.
        /// </summary>
        internal static string kstidRestoreOFDCaption {
            get {
                return ResourceManager.GetString("kstidRestoreOFDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring {0}....
        /// </summary>
        internal static string kstidRestoringMsg {
            get {
                return ResourceManager.GetString("kstidRestoringMsg", resourceCulture);
            }
        }
    }
}
