//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaFieldsDisplayText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaFieldsDisplayText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.PaFieldsDisplayText", typeof(PaFieldsDisplayText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File.
        /// </summary>
        internal static string kstidAudioFile {
            get {
                return ResourceManager.GetString("kstidAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Length.
        /// </summary>
        internal static string kstidAudioLength {
            get {
                return ResourceManager.GetString("kstidAudioLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Offset.
        /// </summary>
        internal static string kstidAudioOffset {
            get {
                return ResourceManager.GetString("kstidAudioOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string kstidComment {
            get {
                return ResourceManager.GetString("kstidComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string kstidCountry {
            get {
                return ResourceManager.GetString("kstidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Pattern.
        /// </summary>
        internal static string kstidCVPattern {
            get {
                return ResourceManager.GetString("kstidCVPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string kstidDataSource {
            get {
                return ResourceManager.GetString("kstidDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source Path.
        /// </summary>
        internal static string kstidDataSourcePath {
            get {
                return ResourceManager.GetString("kstidDataSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string kstidDate {
            get {
                return ResourceManager.GetString("kstidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialect.
        /// </summary>
        internal static string kstidDialect {
            get {
                return ResourceManager.GetString("kstidDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnologue Id.
        /// </summary>
        internal static string kstidEthnologueId {
            get {
                return ResourceManager.GetString("kstidEthnologueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string kstidFamily {
            get {
                return ResourceManager.GetString("kstidFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Translation.
        /// </summary>
        internal static string kstidFreeform {
            get {
                return ResourceManager.GetString("kstidFreeform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloss.
        /// </summary>
        internal static string kstidGloss {
            get {
                return ResourceManager.GetString("kstidGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        internal static string kstidGuid {
            get {
                return ResourceManager.GetString("kstidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Name.
        /// </summary>
        internal static string kstidLanguageName {
            get {
                return ResourceManager.GetString("kstidLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook Ref..
        /// </summary>
        internal static string kstidNotebookRef {
            get {
                return ResourceManager.GetString("kstidNotebookRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthographic.
        /// </summary>
        internal static string kstidOrtho {
            get {
                return ResourceManager.GetString("kstidOrtho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonemic.
        /// </summary>
        internal static string kstidPhonemic {
            get {
                return ResourceManager.GetString("kstidPhonemic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic.
        /// </summary>
        internal static string kstidPhonetic {
            get {
                return ResourceManager.GetString("kstidPhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of Speech.
        /// </summary>
        internal static string kstidPOS {
            get {
                return ResourceManager.GetString("kstidPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string kstidReference {
            get {
                return ResourceManager.GetString("kstidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string kstidRegion {
            get {
                return ResourceManager.GetString("kstidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker&apos;s Gender.
        /// </summary>
        internal static string kstidSpeakerGender {
            get {
                return ResourceManager.GetString("kstidSpeakerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker.
        /// </summary>
        internal static string kstidSpeakerName {
            get {
                return ResourceManager.GetString("kstidSpeakerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone.
        /// </summary>
        internal static string kstidTone {
            get {
                return ResourceManager.GetString("kstidTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcriber.
        /// </summary>
        internal static string kstidTranscriber {
            get {
                return ResourceManager.GetString("kstidTranscriber", resourceCulture);
            }
        }
    }
}
