//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File.
        /// </summary>
        internal static string kstidAudioFile {
            get {
                return ResourceManager.GetString("kstidAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string kstidComment {
            get {
                return ResourceManager.GetString("kstidComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string kstidCountry {
            get {
                return ResourceManager.GetString("kstidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Pattern.
        /// </summary>
        internal static string kstidCVPattern {
            get {
                return ResourceManager.GetString("kstidCVPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialect.
        /// </summary>
        internal static string kstidDialect {
            get {
                return ResourceManager.GetString("kstidDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving vernacular writing systems from the {0}\ndatabase. It&apos;s possible the file {1} is either missing or corrupt.\n\n{2}.
        /// </summary>
        internal static string kstidErrorRetrievingAnalWsMsg {
            get {
                return ResourceManager.GetString("kstidErrorRetrievingAnalWsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the data from the {0} database.\nIt&apos;s possible the file {1} is either missing or\ncorrupt. Reading this data will be skipped.\n\n{2}.
        /// </summary>
        internal static string kstidErrorRetrievingFwDataMsg {
            get {
                return ResourceManager.GetString("kstidErrorRetrievingFwDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving vernacular writing systems from the {0}\ndatabase. It&apos;s possible the file {1} is either missing or corrupt.\n\n{2}.
        /// </summary>
        internal static string kstidErrorRetrievingVernWsMsg {
            get {
                return ResourceManager.GetString("kstidErrorRetrievingVernWsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSDE (SQL Server) cannot be started. It may not be installed.\nThe following error was reported:\n\n{0}\n\nMake sure FieldWorks Language Explorer has been installed..
        /// </summary>
        internal static string kstidErrorStartingMSDE1 {
            get {
                return ResourceManager.GetString("kstidErrorStartingMSDE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSDE (SQL Server) cannot be started. It may not be installed.\nMake sure FieldWorks Language Explorer has been installed..
        /// </summary>
        internal static string kstidErrorStartingMSDE2 {
            get {
                return ResourceManager.GetString("kstidErrorStartingMSDE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnologue Id.
        /// </summary>
        internal static string kstidEthnologueId {
            get {
                return ResourceManager.GetString("kstidEthnologueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string kstidFamily {
            get {
                return ResourceManager.GetString("kstidFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature &apos;{0}&apos; is not a custom feature. It cannot be deleted..
        /// </summary>
        internal static string kstidFeatureCantBeDeletedMsg {
            get {
                return ResourceManager.GetString("kstidFeatureCantBeDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature &apos;{0}&apos; already exists..
        /// </summary>
        internal static string kstidFeatureExistsMsg {
            get {
                return ResourceManager.GetString("kstidFeatureExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Translation.
        /// </summary>
        internal static string kstidFreeform {
            get {
                return ResourceManager.GetString("kstidFreeform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - ({1}).
        /// </summary>
        internal static string kstidFWDataSourceInfo {
            get {
                return ResourceManager.GetString("kstidFWDataSourceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldWorks database {0} is missing..
        /// </summary>
        internal static string kstidFwDBMissing {
            get {
                return ResourceManager.GetString("kstidFwDBMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string kstidGender {
            get {
                return ResourceManager.GetString("kstidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloss.
        /// </summary>
        internal static string kstidGloss {
            get {
                return ResourceManager.GetString("kstidGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Name.
        /// </summary>
        internal static string kstidLanguageName {
            get {
                return ResourceManager.GetString("kstidLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook Ref..
        /// </summary>
        internal static string kstidNotebookRef {
            get {
                return ResourceManager.GetString("kstidNotebookRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string kstidOriginalDate {
            get {
                return ResourceManager.GetString("kstidOriginalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthographic.
        /// </summary>
        internal static string kstidOrtho {
            get {
                return ResourceManager.GetString("kstidOrtho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonemic.
        /// </summary>
        internal static string kstidPhonemic {
            get {
                return ResourceManager.GetString("kstidPhonemic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic.
        /// </summary>
        internal static string kstidPhonetic {
            get {
                return ResourceManager.GetString("kstidPhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of Speech.
        /// </summary>
        internal static string kstidPOS {
            get {
                return ResourceManager.GetString("kstidPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Marker.
        /// </summary>
        internal static string kstidRecMrkr {
            get {
                return ResourceManager.GetString("kstidRecMrkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string kstidReference {
            get {
                return ResourceManager.GetString("kstidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string kstidRegion {
            get {
                return ResourceManager.GetString("kstidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker.
        /// </summary>
        internal static string kstidSpeakerName {
            get {
                return ResourceManager.GetString("kstidSpeakerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone.
        /// </summary>
        internal static string kstidTone {
            get {
                return ResourceManager.GetString("kstidTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcriber.
        /// </summary>
        internal static string kstidTranscriber {
            get {
                return ResourceManager.GetString("kstidTranscriber", resourceCulture);
            }
        }
    }
}
