//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SIL.Pa.Resources {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class PaStrings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("SIL.Pa.Resources.PaStrings", typeof(PaStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulatory features.
        /// </summary>
        internal static string kstidClassBasedOnArticulatoryFeatures {
            get {
                return ResourceManager.GetString("kstidClassBasedOnArticulatoryFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary features.
        /// </summary>
        internal static string kstidClassBasedOnBinaryFeatures {
            get {
                return ResourceManager.GetString("kstidClassBasedOnBinaryFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other classes.
        /// </summary>
        internal static string kstidClassBasedOnOtherClasses {
            get {
                return ResourceManager.GetString("kstidClassBasedOnOtherClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic characters.
        /// </summary>
        internal static string kstidClassBasedOnPhoneticChars {
            get {
                return ResourceManager.GetString("kstidClassBasedOnPhoneticChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string kstidCloseClassSymbol {
            get {
                return ResourceManager.GetString("kstidCloseClassSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of .
        /// </summary>
        internal static string kstidCopyOfPrefix {
            get {
                return ResourceManager.GetString("kstidCopyOfPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} &apos;{1}&apos;?.
        /// </summary>
        internal static string kstidDeleteItemMsg {
            get {
                return ResourceManager.GetString("kstidDeleteItemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Executables (*.exe;*.com;*.pif;*.bat;*.cmd)|*.exe;*.com;*.pif;*.bat;*.cmd.
        /// </summary>
        internal static string kstidFileTypeAllExe {
            get {
                return ResourceManager.GetString("kstidFileTypeAllExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string kstidFileTypeAllFiles {
            get {
                return ResourceManager.GetString("kstidFileTypeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Files (*.html)|*.html.
        /// </summary>
        internal static string kstidFileTypeHTML {
            get {
                return ResourceManager.GetString("kstidFileTypeHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Projects (*.pap)|*.pap.
        /// </summary>
        internal static string kstidFileTypePAProject {
            get {
                return ResourceManager.GetString("kstidFileTypePAProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} XML Files (*.paxml)|*.paxml.
        /// </summary>
        internal static string kstidFileTypePAXML {
            get {
                return ResourceManager.GetString("kstidFileTypePAXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format (*.rtf)|*.rtf.
        /// </summary>
        internal static string kstidFiletypeRTF {
            get {
                return ResourceManager.GetString("kstidFiletypeRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Analyzer MP3 Files (*.mp3)|*.mp3.
        /// </summary>
        internal static string kstidFiletypeSASoundMP3 {
            get {
                return ResourceManager.GetString("kstidFiletypeSASoundMP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Analyzer Wave Files (*.wav)|*.wav.
        /// </summary>
        internal static string kstidFiletypeSASoundWave {
            get {
                return ResourceManager.GetString("kstidFiletypeSASoundWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Analyzer WMA Files (*.wma)|*.wma.
        /// </summary>
        internal static string kstidFiletypeSASoundWMA {
            get {
                return ResourceManager.GetString("kstidFiletypeSASoundWMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Files (*.db)|*.db.
        /// </summary>
        internal static string kstidFileTypeToolboxDB {
            get {
                return ResourceManager.GetString("kstidFileTypeToolboxDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlinear Toolbox Files (*.itx)|*.itx.
        /// </summary>
        internal static string kstidFileTypeToolboxITX {
            get {
                return ResourceManager.GetString("kstidFileTypeToolboxITX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml.
        /// </summary>
        internal static string kstidFileTypeXML {
            get {
                return ResourceManager.GetString("kstidFileTypeXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT Files (*.xslt)|*.xslt.
        /// </summary>
        internal static string kstidFileTypeXSLT {
            get {
                return ResourceManager.GetString("kstidFileTypeXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string kstidMinusFeatureSymbol {
            get {
                return ResourceManager.GetString("kstidMinusFeatureSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string kstidOpenClassSymbol {
            get {
                return ResourceManager.GetString("kstidOpenClassSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string kstidPlusFeatureSymbol {
            get {
                return ResourceManager.GetString("kstidPlusFeatureSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string kstidQuerySearchingMsg {
            get {
                return ResourceManager.GetString("kstidQuerySearchingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes?.
        /// </summary>
        internal static string kstidSaveChangesMsg {
            get {
                return ResourceManager.GetString("kstidSaveChangesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string kstidSaveFileDialogGenericCaption {
            get {
                return ResourceManager.GetString("kstidSaveFileDialogGenericCaption", resourceCulture);
            }
        }
    }
}
