//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SIL.SpeechTools.Utils.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("SIL.SpeechTools.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static Bitmap kimidCollapse {
            get {
                object obj = ResourceManager.GetObject("kimidCollapse", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap kimidExpand {
            get {
                object obj = ResourceManager.GetObject("kimidExpand", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap kimidSilLogo {
            get {
                object obj = ResourceManager.GetObject("kimidSilLogo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap kimidSilLogo1 {
            get {
                object obj = ResourceManager.GetObject("kimidSilLogo1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        internal static string kstidCnvtrGridCnvtrHdg {
            get {
                return ResourceManager.GetString("kstidCnvtrGridCnvtrHdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Font.
        /// </summary>
        internal static string kstidCnvtrGridFontHdg {
            get {
                return ResourceManager.GetString("kstidCnvtrGridFontHdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription.
        /// </summary>
        internal static string kstidCnvtrGridTransHdg {
            get {
                return ResourceManager.GetString("kstidCnvtrGridTransHdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing SA Document reader.\n\n{0}.
        /// </summary>
        internal static string kstidErrorInitializingDocReader {
            get {
                return ResourceManager.GetString("kstidErrorInitializingDocReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing SA Document writer.\n\n{0}.
        /// </summary>
        internal static string kstidErrorInitializingDocWriter {
            get {
                return ResourceManager.GetString("kstidErrorInitializingDocWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening Speech Analyzer database.\n\n{0}\n\nWould you like to try restoring the from the backup?.
        /// </summary>
        internal static string kstidErrorOpeningSADB {
            get {
                return ResourceManager.GetString("kstidErrorOpeningSADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Speech Analyzer database.\n\n{0}.
        /// </summary>
        internal static string kstidErrorSavingSADB {
            get {
                return ResourceManager.GetString("kstidErrorSavingSADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string kstidFileTypeAll {
            get {
                return ResourceManager.GetString("kstidFileTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Files (*.cct)|*.cct.
        /// </summary>
        internal static string kstidFileTypeCCFile {
            get {
                return ResourceManager.GetString("kstidFileTypeCCFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECkit Uncompiled Mapping Files (*.map)|*.map.
        /// </summary>
        internal static string kstidFileTypeMapFile {
            get {
                return ResourceManager.GetString("kstidFileTypeMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECkit Compiled Mapping Files (*.tec)|*.tec.
        /// </summary>
        internal static string kstidFileTypeTecFile {
            get {
                return ResourceManager.GetString("kstidFileTypeTecFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} records).
        /// </summary>
        internal static string kstidHierarchicalRowChildCountLongFmt {
            get {
                return ResourceManager.GetString("kstidHierarchicalRowChildCountLongFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} rec.).
        /// </summary>
        internal static string kstidHierarchicalRowChildCountMedFmt {
            get {
                return ResourceManager.GetString("kstidHierarchicalRowChildCountMedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string kstidHierarchicalRowChildCountShortFmt {
            get {
                return ResourceManager.GetString("kstidHierarchicalRowChildCountShortFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transcription was found for the specified file:
        ///{0},
        ///
        ///An existing transcription was found for the file:
        ///{1},
        ///
        ///The audio data for both files is identical. 
        ///What would you like to do?.
        /// </summary>
        internal static string kstidIdenticalMD5Msg {
            get {
                return ResourceManager.GetString("kstidIdenticalMD5Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid MusicXML file.\n\nFile will not be loaded..
        /// </summary>
        internal static string kstidInvalidMusicXMLFile {
            get {
                return ResourceManager.GetString("kstidInvalidMusicXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} is not a valid wave file..
        /// </summary>
        internal static string kstidInvalidWaveFile {
            get {
                return ResourceManager.GetString("kstidInvalidWaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors were encountered while validating {0}:\n\n{1}.
        /// </summary>
        internal static string kstidMusicXMLValidationErrMsg {
            get {
                return ResourceManager.GetString("kstidMusicXMLValidationErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Converter Mapping File.
        /// </summary>
        internal static string kstidOFDFindConverterCaption {
            get {
                return ResourceManager.GetString("kstidOFDFindConverterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio file &apos;{0}&apos; does not exist.\nWould you like its record removed from the old database?.
        /// </summary>
        internal static string kstidOldDbAudioFileMissingMsg {
            get {
                return ResourceManager.GetString("kstidOldDbAudioFileMissingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions of Speech Analyzer 3.0 before Beta 4 stored audio file\ntranscriptions in a central database. The method of storing an\naudio file’s transcription has changed so each transcribed audio\nfile possesses a companion file containing those transcriptions.\n\nThe central transcription database has been detected. Click OK\nto begin the process of converting the transcription data from the\ncentral database to individual companion files to the audio files..
        /// </summary>
        internal static string kstidOldDbConverionMsg {
            get {
                return ResourceManager.GetString("kstidOldDbConverionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to save the transcriptions for {0} in a location for which you do not have write access. Please specify another location in which to make a copy of {1} along with its transcription file ({2})..
        /// </summary>
        internal static string kstidReadOnlyFolderMsg {
            get {
                return ResourceManager.GetString("kstidReadOnlyFolderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The failed database has been renamed to {0}..
        /// </summary>
        internal static string kstidSADBRestoreCancelled {
            get {
                return ResourceManager.GetString("kstidSADBRestoreCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speech Analyzer database could not be restored from backup.\n\n{0}\n\nThe failed database has been renamed to {1}..
        /// </summary>
        internal static string kstidSADBRestoreFailed {
            get {
                return ResourceManager.GetString("kstidSADBRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speech Analyzer database was successfully restored from backup.\n\nThe failed database has been renamed to {0}..
        /// </summary>
        internal static string kstidSADBRestoreSucceeded {
            get {
                return ResourceManager.GetString("kstidSADBRestoreSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be found..
        /// </summary>
        internal static string kstidWaveFileNotFound {
            get {
                return ResourceManager.GetString("kstidWaveFileNotFound", resourceCulture);
            }
        }
    }
}
