//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.FFSearchEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.FFSearchEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment after.
        /// </summary>
        internal static string kstidEnvironmentAfter {
            get {
                return ResourceManager.GetString("kstidEnvironmentAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment before.
        /// </summary>
        internal static string kstidEnvironmentBefore {
            get {
                return ResourceManager.GetString("kstidEnvironmentBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular diacritic placeholder syntax in {0}..
        /// </summary>
        internal static string kstidIrregularDiacriticPlaceholderErr {
            get {
                return ResourceManager.GetString("kstidIrregularDiacriticPlaceholderErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched braces found in the {0}..
        /// </summary>
        internal static string kstidMismatchedBracesErr {
            get {
                return ResourceManager.GetString("kstidMismatchedBracesErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched brackets found in the {0}..
        /// </summary>
        internal static string kstidMismatchedBracketsErr {
            get {
                return ResourceManager.GetString("kstidMismatchedBracketsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched brackets or braces found in the {0}..
        /// </summary>
        internal static string kstidMismatchedBracketsOrBracesErr {
            get {
                return ResourceManager.GetString("kstidMismatchedBracketsOrBracesErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misplaced diacritic in {0}..
        /// </summary>
        internal static string kstidMisplacedDiacriticErr {
            get {
                return ResourceManager.GetString("kstidMisplacedDiacriticErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the one-or-more symbol is present in the environment before, it must be  at the beginning..
        /// </summary>
        internal static string kstidOneOrMoreBeginningErr {
            get {
                return ResourceManager.GetString("kstidOneOrMoreBeginningErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the one-or-more symbol is present in the environment after, it must be  at the end..
        /// </summary>
        internal static string kstidOneOrMoreEndingErr {
            get {
                return ResourceManager.GetString("kstidOneOrMoreEndingErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the {0}..
        /// </summary>
        internal static string kstidParsedToNothingError {
            get {
                return ResourceManager.GetString("kstidParsedToNothingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is empty..
        /// </summary>
        internal static string kstidPatternEmptyErr {
            get {
                return ResourceManager.GetString("kstidPatternEmptyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error. Pattern is not\nin the correct format: {0}.
        /// </summary>
        internal static string kstidPatternSyntaxError {
            get {
                return ResourceManager.GetString("kstidPatternSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search item.
        /// </summary>
        internal static string kstidSearchItem {
            get {
                return ResourceManager.GetString("kstidSearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in {0}..
        /// </summary>
        internal static string kstidSyntaxErr {
            get {
                return ResourceManager.GetString("kstidSyntaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many diacritic placeholders between a single set of brackets in the {0}..
        /// </summary>
        internal static string kstidTooManyDiacriticPlaceholdersErr {
            get {
                return ResourceManager.GetString("kstidTooManyDiacriticPlaceholdersErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many one-or-more symbols (+) found in {0}. Only one is allowed..
        /// </summary>
        internal static string kstidTooManyOneOrMoreErr {
            get {
                return ResourceManager.GetString("kstidTooManyOneOrMoreErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many zero-or-more symbols (*) found in {0}. Only one is allowed..
        /// </summary>
        internal static string kstidTooManyZeroOrMoreErr {
            get {
                return ResourceManager.GetString("kstidTooManyZeroOrMoreErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-or-more symbol cannot be in the {0} with the one-or-more symbol..
        /// </summary>
        internal static string kstidZeroAndOneOrMoreFoundErr {
            get {
                return ResourceManager.GetString("kstidZeroAndOneOrMoreFoundErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-or-more and one-or-more symbols are not allowed in the search item..
        /// </summary>
        internal static string kstidZeroOneOrMoreFoundInSrchItemErr {
            get {
                return ResourceManager.GetString("kstidZeroOneOrMoreFoundInSrchItemErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the zero-or-more symbol is present in the environment before, it must be  at the beginning..
        /// </summary>
        internal static string kstidZeroOrMoreBeginningErr {
            get {
                return ResourceManager.GetString("kstidZeroOrMoreBeginningErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the zero-or-more symbol is present in the environment after, it must be  at the end..
        /// </summary>
        internal static string kstidZeroOrMoreEndingErr {
            get {
                return ResourceManager.GetString("kstidZeroOrMoreEndingErr", resourceCulture);
            }
        }
    }
}
