//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.FFSearchEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Pa.FFSearchEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after environment.
        /// </summary>
        internal static string kstidAfterEnvironmentText {
            get {
                return ResourceManager.GetString("kstidAfterEnvironmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before environment.
        /// </summary>
        internal static string kstidBeforeEnvironmentText {
            get {
                return ResourceManager.GetString("kstidBeforeEnvironmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in after environment..
        /// </summary>
        internal static string kstidEnvAfterSyntaxError {
            get {
                return ResourceManager.GetString("kstidEnvAfterSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in before environment..
        /// </summary>
        internal static string kstidEnvBeforeSyntaxError {
            get {
                return ResourceManager.GetString("kstidEnvBeforeSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in search item..
        /// </summary>
        internal static string kstidItemSyntaxError {
            get {
                return ResourceManager.GetString("kstidItemSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the {0}..
        /// </summary>
        internal static string kstidPatternParsedToNothingError {
            get {
                return ResourceManager.GetString("kstidPatternParsedToNothingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error. Pattern is not\nin the correct format: {0}.
        /// </summary>
        internal static string kstidPatternSyntaxError {
            get {
                return ResourceManager.GetString("kstidPatternSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search item.
        /// </summary>
        internal static string kstidSearchItemText {
            get {
                return ResourceManager.GetString("kstidSearchItemText", resourceCulture);
            }
        }
    }
}
