//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Pa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepTempProjectInventoryFile {
            get {
                return ((bool)(this["KeepTempProjectInventoryFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastProjectLoaded {
            get {
                return ((string)(this["LastProjectLoaded"]));
            }
            set {
                this["LastProjectLoaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserInterfaceLanguage {
            get {
                return ((string)(this["UserInterfaceLanguage"]));
            }
            set {
                this["UserInterfaceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowMsgWhenGatheringFwInfo {
            get {
                return ((bool)(this["ShowMsgWhenGatheringFwInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("550, 450")]
        public global::System.Drawing.Size MinimumViewWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MinimumViewWindowSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UncertainGroupAbsentPhoneChars {
            get {
                return ((string)(this["UncertainGroupAbsentPhoneChars"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UncertainGroupAbsentPhoneChar {
            get {
                return ((string)(this["UncertainGroupAbsentPhoneChar"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSplashScreen {
            get {
                return ((bool)(this["ShowSplashScreen"]));
            }
            set {
                this["ShowSplashScreen"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string ConsonantSymbol {
            get {
                return ((string)(this["ConsonantSymbol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public string VowelSymbol {
            get {
                return ((string)(this["VowelSymbol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WordBreakCharacters {
            get {
                return ((string)(this["WordBreakCharacters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MaximumAllowedRecentlyUsedQueries {
            get {
                return ((int)(this["MaximumAllowedRecentlyUsedQueries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color RecordViewFieldLabelColor {
            get {
                return ((global::System.Drawing.Color)(this["RecordViewFieldLabelColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color WordListGridColor {
            get {
                return ((global::System.Drawing.Color)(this["WordListGridColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertPatternsWithTranscriptionChanges {
            get {
                return ((bool)(this["ConvertPatternsWithTranscriptionChanges"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastViewShowing {
            get {
                return ((string)(this["LastViewShowing"]));
            }
            set {
                this["LastViewShowing"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SkipAdditionalProcessingWhenPhonesAreLoaded {
            get {
                return ((bool)(this["SkipAdditionalProcessingWhenPhonesAreLoaded"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepTempDistributionChartExportFile {
            get {
                return ((bool)(this["KeepTempDistributionChartExportFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OFD_LastFileTypeChosen_DataSource {
            get {
                return ((int)(this["OFD_LastFileTypeChosen_DataSource"]));
            }
            set {
                this["OFD_LastFileTypeChosen_DataSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OFD_LastFileTypeChosen_DataSourceXslt {
            get {
                return ((int)(this["OFD_LastFileTypeChosen_DataSourceXslt"]));
            }
            set {
                this["OFD_LastFileTypeChosen_DataSourceXslt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenHtmlDistChartAfterExport {
            get {
                return ((bool)(this["OpenHtmlDistChartAfterExport"]));
            }
            set {
                this["OpenHtmlDistChartAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenHtmlDataCorpusAfterExport {
            get {
                return ((bool)(this["OpenHtmlDataCorpusAfterExport"]));
            }
            set {
                this["OpenHtmlDataCorpusAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepTempDataCorpusExportFile {
            get {
                return ((bool)(this["KeepTempDataCorpusExportFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenHtmlSearchResultAfterExport {
            get {
                return ((bool)(this["OpenHtmlSearchResultAfterExport"]));
            }
            set {
                this["OpenHtmlSearchResultAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepTempSearchResultExportFile {
            get {
                return ((bool)(this["KeepTempSearchResultExportFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepTempProjectCssXhtmlFile {
            get {
                return ((bool)(this["KeepTempProjectCssXhtmlFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepTempCVChartBuilderFile {
            get {
                return ((bool)(this["KeepTempCVChartBuilderFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225, 225, 225")]
        public global::System.Drawing.Color ConsonantChartGridColor {
            get {
                return ((global::System.Drawing.Color)(this["ConsonantChartGridColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225, 225, 225")]
        public global::System.Drawing.Color VowelChartGridColor {
            get {
                return ((global::System.Drawing.Color)(this["VowelChartGridColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ConsonantChartColHdrHeight {
            get {
                return ((int)(this["ConsonantChartColHdrHeight"]));
            }
            set {
                this["ConsonantChartColHdrHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ConsonantChartRowHdrWidth {
            get {
                return ((int)(this["ConsonantChartRowHdrWidth"]));
            }
            set {
                this["ConsonantChartRowHdrWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int VowelChartColHdrHeight {
            get {
                return ((int)(this["VowelChartColHdrHeight"]));
            }
            set {
                this["VowelChartColHdrHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int VowelChartRowHdrWidth {
            get {
                return ((int)(this["VowelChartRowHdrWidth"]));
            }
            set {
                this["VowelChartRowHdrWidth"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepTempCVChartExportFile {
            get {
                return ((bool)(this["KeepTempCVChartExportFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenHtmlCVChartAfterExport {
            get {
                return ((bool)(this["OpenHtmlCVChartAfterExport"]));
            }
            set {
                this["OpenHtmlCVChartAfterExport"] = value;
            }
        }
        
        /// <summary>
        /// When true and temporary export files are written to disk, the temporary XML is nicely indented and formatted for better human readability.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When true and temporary export files are written to disk, the temporary XML is ni" +
            "cely indented and formatted for better human readability.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TidyUpTempExportFilesAfterSaving {
            get {
                return ((bool)(this["TidyUpTempExportFilesAfterSaving"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenWordXmlDataCorpusAfterExport {
            get {
                return ((bool)(this["OpenWordXmlDataCorpusAfterExport"]));
            }
            set {
                this["OpenWordXmlDataCorpusAfterExport"] = value;
            }
        }
        
        /// <summary>
        /// Full path is valid here. When left empty, the default application is used.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("Full path is valid here. When left empty, the default application is used.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppThatOpensHtml {
            get {
                return ((string)(this["AppThatOpensHtml"]));
            }
            set {
                this["AppThatOpensHtml"] = value;
            }
        }
        
        /// <summary>
        /// When left empty, the default application is used.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("When left empty, the default application is used.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Winword.exe")]
        public string AppThatOpensWordXml {
            get {
                return ((string)(this["AppThatOpensWordXml"]));
            }
            set {
                this["AppThatOpensWordXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenWordXmlSearchResultAfterExport {
            get {
                return ((bool)(this["OpenWordXmlSearchResultAfterExport"]));
            }
            set {
                this["OpenWordXmlSearchResultAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenWordXmlCVChartAfterExport {
            get {
                return ((bool)(this["OpenWordXmlCVChartAfterExport"]));
            }
            set {
                this["OpenWordXmlCVChartAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenWordXmlDistChartAfterExport {
            get {
                return ((bool)(this["OpenWordXmlDistChartAfterExport"]));
            }
            set {
                this["OpenWordXmlDistChartAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ethnologue.com/language_index.asp")]
        public string EthnologueIndexPage {
            get {
                return ((string)(this["EthnologueIndexPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ethnologue.com/language_index.asp?letter={0}")]
        public string EthnologueFirstLetterOfNameSearch {
            get {
                return ((string)(this["EthnologueFirstLetterOfNameSearch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ethnologue.com/show_language.asp?code={0}")]
        public string EthnologueCodeSearch {
            get {
                return ((string)(this["EthnologueCodeSearch"]));
            }
        }
        
        /// <summary>
        /// This is a subfolder of the project&apos;s folder where temp. files are created during exports and while data sources are read. This value only matters when those temp. files are saved. There are other settings that can prevent the temp. files from being saved. If this value is left blank, temp. files are saved in the project folder.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute(@"This is a subfolder of the project's folder where temp. files are created during exports and while data sources are read. This value only matters when those temp. files are saved. There are other settings that can prevent the temp. files from being saved. If this value is left blank, temp. files are saved in the project folder.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemporaryProcessingFiles")]
        public string TempProcessingFilesFolder {
            get {
                return ((string)(this["TempProcessingFilesFolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool HtmlVowelChartVisible {
            get {
                return ((bool)(this["HtmlVowelChartVisible"]));
            }
            set {
                this["HtmlVowelChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool HtmlConsonantChartVisible {
            get {
                return ((bool)(this["HtmlConsonantChartVisible"]));
            }
            set {
                this["HtmlConsonantChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings DefineClassDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["DefineClassDlg"]));
            }
            set {
                this["DefineClassDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings ClassesDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["ClassesDlg"]));
            }
            set {
                this["ClassesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DefineClassDlgSplit1Loc {
            get {
                return ((int)(this["DefineClassDlgSplit1Loc"]));
            }
            set {
                this["DefineClassDlgSplit1Loc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DefineClassDlgSplit2Loc {
            get {
                return ((int)(this["DefineClassDlgSplit2Loc"]));
            }
            set {
                this["DefineClassDlgSplit2Loc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DefineClassDlgSplit3Loc {
            get {
                return ((int)(this["DefineClassDlgSplit3Loc"]));
            }
            set {
                this["DefineClassDlgSplit3Loc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.SortOrder ClassesDlgClassListViewSortOrder {
            get {
                return ((global::System.Windows.Forms.SortOrder)(this["ClassesDlgClassListViewSortOrder"]));
            }
            set {
                this["ClassesDlgClassListViewSortOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ClassesDlgClassListViewSortedColumn {
            get {
                return ((int)(this["ClassesDlgClassListViewSortedColumn"]));
            }
            set {
                this["ClassesDlgClassListViewSortedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ClassesDlgClassListViewColWidth0 {
            get {
                return ((int)(this["ClassesDlgClassListViewColWidth0"]));
            }
            set {
                this["ClassesDlgClassListViewColWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ClassesDlgClassListViewColWidth1 {
            get {
                return ((int)(this["ClassesDlgClassListViewColWidth1"]));
            }
            set {
                this["ClassesDlgClassListViewColWidth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ClassesDlgClassListViewColWidth2 {
            get {
                return ((int)(this["ClassesDlgClassListViewColWidth2"]));
            }
            set {
                this["ClassesDlgClassListViewColWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings BackupDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["BackupDlg"]));
            }
            set {
                this["BackupDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings RestoreDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["RestoreDlg"]));
            }
            set {
                this["RestoreDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XYChartVwClassListViewColWidth0 {
            get {
                return ((int)(this["XYChartVwClassListViewColWidth0"]));
            }
            set {
                this["XYChartVwClassListViewColWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchVwClassListViewColWidth0 {
            get {
                return ((int)(this["SearchVwClassListViewColWidth0"]));
            }
            set {
                this["SearchVwClassListViewColWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings AmbiguousSequencesDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["AmbiguousSequencesDlg"]));
            }
            set {
                this["AmbiguousSequencesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings CustomFieldsDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["CustomFieldsDlg"]));
            }
            set {
                this["CustomFieldsDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings FeaturesDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["FeaturesDlg"]));
            }
            set {
                this["FeaturesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings TranscriptionChangesDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["TranscriptionChangesDlg"]));
            }
            set {
                this["TranscriptionChangesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings ProjectSettingsDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["ProjectSettingsDlg"]));
            }
            set {
                this["ProjectSettingsDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings SaveSearchQuerDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["SaveSearchQuerDlg"]));
            }
            set {
                this["SaveSearchQuerDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings SaveDistChartDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["SaveDistChartDlg"]));
            }
            set {
                this["SaveDistChartDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings SFDataSourcePropertiesDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["SFDataSourcePropertiesDlg"]));
            }
            set {
                this["SFDataSourcePropertiesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings FindDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["FindDlg"]));
            }
            set {
                this["FindDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings UndefinedPhoneticCharactersDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["UndefinedPhoneticCharactersDlg"]));
            }
            set {
                this["UndefinedPhoneticCharactersDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings OptionsDialog {
            get {
                return ((global::SilUtils.FormSettings)(this["OptionsDialog"]));
            }
            set {
                this["OptionsDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings FwDataSourcePropertiesDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["FwDataSourcePropertiesDlg"]));
            }
            set {
                this["FwDataSourcePropertiesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings FwProjectsDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["FwProjectsDlg"]));
            }
            set {
                this["FwProjectsDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int FeaturesDlgSplitLoc {
            get {
                return ((int)(this["FeaturesDlgSplitLoc"]));
            }
            set {
                this["FeaturesDlgSplitLoc"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int FeaturesDlgGridExtraRowHeight {
            get {
                return ((int)(this["FeaturesDlgGridExtraRowHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AmbiguousSequencesDlgGridExtraRowHeight {
            get {
                return ((int)(this["AmbiguousSequencesDlgGridExtraRowHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TranscriptionChangesDlgGridExtraRowHeight {
            get {
                return ((int)(this["TranscriptionChangesDlgGridExtraRowHeight"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings FiltersDlg {
            get {
                return ((global::SilUtils.FormSettings)(this["FiltersDlg"]));
            }
            set {
                this["FiltersDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int FwProjectsDlgSplitLoc {
            get {
                return ((int)(this["FwProjectsDlgSplitLoc"]));
            }
            set {
                this["FwProjectsDlgSplitLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FindDlgFindWhat {
            get {
                return ((string)(this["FindDlgFindWhat"]));
            }
            set {
                this["FindDlgFindWhat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool FindDlgMatchCase {
            get {
                return ((bool)(this["FindDlgMatchCase"]));
            }
            set {
                this["FindDlgMatchCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool FindDlgMatchEntireWord {
            get {
                return ((bool)(this["FindDlgMatchEntireWord"]));
            }
            set {
                this["FindDlgMatchEntireWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool FindDlgStartsWith {
            get {
                return ((bool)(this["FindDlgStartsWith"]));
            }
            set {
                this["FindDlgStartsWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool FindDlgRegEx {
            get {
                return ((bool)(this["FindDlgRegEx"]));
            }
            set {
                this["FindDlgRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool FindDlgReverse {
            get {
                return ((bool)(this["FindDlgReverse"]));
            }
            set {
                this["FindDlgReverse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FindDlgSearchCollapsedGroups {
            get {
                return ((bool)(this["FindDlgSearchCollapsedGroups"]));
            }
            set {
                this["FindDlgSearchCollapsedGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastFolderForOpenProjectDlg {
            get {
                return ((string)(this["LastFolderForOpenProjectDlg"]));
            }
            set {
                this["LastFolderForOpenProjectDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings FeaturesDlgPhoneGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["FeaturesDlgPhoneGrid"]));
            }
            set {
                this["FeaturesDlgPhoneGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MRUList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MRUList"]));
            }
            set {
                this["MRUList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings FiltersDlgGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["FiltersDlgGrid"]));
            }
            set {
                this["FiltersDlgGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int FiltersDlgSplitLoc {
            get {
                return ((int)(this["FiltersDlgSplitLoc"]));
            }
            set {
                this["FiltersDlgSplitLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings AmbiguousSequencesDlgGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["AmbiguousSequencesDlgGrid"]));
            }
            set {
                this["AmbiguousSequencesDlgGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings RestoreDlgGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["RestoreDlgGrid"]));
            }
            set {
                this["RestoreDlgGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings CustomFieldsDlgGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["CustomFieldsDlgGrid"]));
            }
            set {
                this["CustomFieldsDlgGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings FwDataSourcePropertiesDlgGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["FwDataSourcePropertiesDlgGrid"]));
            }
            set {
                this["FwDataSourcePropertiesDlgGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings ProjectSettingsDlgGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["ProjectSettingsDlgGrid"]));
            }
            set {
                this["ProjectSettingsDlgGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings UndefinedPhoneticCharactersDlgCharsGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["UndefinedPhoneticCharactersDlgCharsGrid"]));
            }
            set {
                this["UndefinedPhoneticCharactersDlgCharsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings UndefinedPhoneticCharactersDlgWhereGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["UndefinedPhoneticCharactersDlgWhereGrid"]));
            }
            set {
                this["UndefinedPhoneticCharactersDlgWhereGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings TranscriptionChangesGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["TranscriptionChangesGrid"]));
            }
            set {
                this["TranscriptionChangesGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int UndefinedPhoneticCharactersDlgSplitLoc {
            get {
                return ((int)(this["UndefinedPhoneticCharactersDlgSplitLoc"]));
            }
            set {
                this["UndefinedPhoneticCharactersDlgSplitLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings OptionsDialogFontGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["OptionsDialogFontGrid"]));
            }
            set {
                this["OptionsDialogFontGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.GridSettings SFDataSourcePropertiesDlgGrid {
            get {
                return ((global::SilUtils.GridSettings)(this["SFDataSourcePropertiesDlgGrid"]));
            }
            set {
                this["SFDataSourcePropertiesDlgGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SFDataSourcePropertiesDlgSplitLoc {
            get {
                return ((int)(this["SFDataSourcePropertiesDlgSplitLoc"]));
            }
            set {
                this["SFDataSourcePropertiesDlgSplitLoc"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font UIFont {
            get {
                return ((global::System.Drawing.Font)(this["UIFont"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings MainWindow {
            get {
                return ((global::SilUtils.FormSettings)(this["MainWindow"]));
            }
            set {
                this["MainWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings DataCorpusVw {
            get {
                return ((global::SilUtils.FormSettings)(this["DataCorpusVw"]));
            }
            set {
                this["DataCorpusVw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings SearchVw {
            get {
                return ((global::SilUtils.FormSettings)(this["SearchVw"]));
            }
            set {
                this["SearchVw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings VowelChartVw {
            get {
                return ((global::SilUtils.FormSettings)(this["VowelChartVw"]));
            }
            set {
                this["VowelChartVw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings ConsonantChartVw {
            get {
                return ((global::SilUtils.FormSettings)(this["ConsonantChartVw"]));
            }
            set {
                this["ConsonantChartVw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilUtils.FormSettings XYChartVw {
            get {
                return ((global::SilUtils.FormSettings)(this["XYChartVw"]));
            }
            set {
                this["XYChartVw"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReloadProjectsOnActivate {
            get {
                return ((bool)(this["ReloadProjectsOnActivate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SaDownloadLink {
            get {
                return ((string)(this["SaDownloadLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SaWebsiteLink {
            get {
                return ((string)(this["SaWebsiteLink"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenXLingPaperDataCorpusAfterExport {
            get {
                return ((bool)(this["OpenXLingPaperDataCorpusAfterExport"]));
            }
            set {
                this["OpenXLingPaperDataCorpusAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppThatOpensXLingPaperXML {
            get {
                return ((string)(this["AppThatOpensXLingPaperXML"]));
            }
            set {
                this["AppThatOpensXLingPaperXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenXLingPaperSearchResultAfterExport {
            get {
                return ((bool)(this["OpenXLingPaperSearchResultAfterExport"]));
            }
            set {
                this["OpenXLingPaperSearchResultAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenXLingPaperCVChartAfterExport {
            get {
                return ((bool)(this["OpenXLingPaperCVChartAfterExport"]));
            }
            set {
                this["OpenXLingPaperCVChartAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenXLingPaperDistChartAfterExport {
            get {
                return ((bool)(this["OpenXLingPaperDistChartAfterExport"]));
            }
            set {
                this["OpenXLingPaperDistChartAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int LocalizeDlgSplitterPos {
            get {
                return ((int)(this["LocalizeDlgSplitterPos"]));
            }
            set {
                this["LocalizeDlgSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Rectangle LocalizeDlgBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["LocalizeDlgBounds"]));
            }
            set {
                this["LocalizeDlgBounds"] = value;
            }
        }
    }
}
